import { randomBytes } from 'node:crypto';

export function generateAuthSecret(): string {
  return randomBytes(32).toString('base64url');
}

export interface BuildConfigFileOptions {
  /**
   * Contents of the template's `config.example.yml`, used as the base so its comments and commented-out sections
   * reach the user.
   */
  readonly example?: string;
  readonly secret?: string;
}

/**
 * Builds the `config.yml` a generated application starts with.
 *
 * The template's own `config.example.yml` is the base rather than a file assembled here. It is the one place that
 * documents what an application can be configured with — the notification channels, the LLM services, the additional
 * database connections — and every line of it is written for someone about to edit it. A file generated from scratch
 * carried a fraction of that and went stale the moment the example grew.
 *
 * Only the secrets are filled in, because they are the one thing the example cannot ship: `auth.secret` has no safe
 * default, and an application without it starts in install mode on a secret regenerated every boot, which invalidates
 * every session on restart. Everything else the example already answers, including the database, which a generated
 * application changes in `server/config/database.ts` rather than here.
 */
export function buildConfigFile(options: BuildConfigFileOptions = {}): string {
  const secret = options.secret ?? generateAuthSecret();
  const base =
    options.example === undefined ? FALLBACK_CONFIG : retitle(options.example);

  const withAuth = setSectionSecret(base, 'auth', secret);
  const withSession = setSectionSecret(withAuth, 'session', secret);

  return `${withSession.trimEnd()}\n`;
}

const GENERATED_HEADER = '# Generated by @nocobase/create-app.';

/**
 * Replaces the example's opening instruction, which stops being true the moment the file is the `config.yml` it was
 * telling the reader to make. A leading comment that says nothing of the sort is left alone and the header goes above
 * it, since an example is not required to open with an instruction at all.
 */
function retitle(example: string): string {
  const lines = example.split(/\r?\n/u);
  const opening = lines[0] ?? '';

  return /^#.*\bcopy\b.*\bconfig\.yml\b/iu.test(opening)
    ? [GENERATED_HEADER, ...lines.slice(1)].join('\n')
    : [GENERATED_HEADER, ...lines].join('\n');
}

/**
 * Written when the template ships no `config.example.yml`, so a generated application always has the secrets it
 * cannot start without. Everything else falls back to the defaults in the application's own `server/config/`.
 */
const FALLBACK_CONFIG = `${GENERATED_HEADER}\n`;

/** Indentation for a key inserted into a section that has none to copy. */
const DEFAULT_INDENT = '  ';

/**
 * Writes `secret` into a top-level section, whichever of the four shapes the example happens to use.
 *
 * `config.example.yml` uses two of them today and the distinction is deliberate on its side: `auth` is a live section
 * whose `secret` is commented out among live siblings, while `session` is commented out in its entirety because an
 * application that sets nothing there still runs. Both have to end up live and carrying the same value, and a
 * template is free to change which shape it uses, so all four are handled rather than the two in front of us.
 *
 * Uncommenting rather than appending is what keeps the surrounding comments — the line explaining how to generate a
 * secret, and the one saying the session secret matches `auth.secret` — attached to the values they explain. It also
 * avoids the failure appending would cause: a second top-level `auth:` is a duplicate key, which is an error rather
 * than an override.
 */
function setSectionSecret(
  contents: string,
  section: string,
  secret: string,
): string {
  const lines = contents.split(/\r?\n/u);
  const live = lines.findIndex((line) =>
    new RegExp(`^${section}\\s*:`, 'u').test(line),
  );

  if (live !== -1) {
    return fillSectionSecret(lines, live, secret).join('\n');
  }

  const commented = lines.findIndex((line) =>
    new RegExp(`^#\\s*${section}\\s*:`, 'u').test(line),
  );

  if (commented !== -1) {
    return fillSectionSecret(
      uncommentBlock(lines, commented),
      commented,
      secret,
    ).join('\n');
  }

  return [
    contents.trimEnd(),
    '',
    `${section}:`,
    `${DEFAULT_INDENT}secret: ${yamlString(secret)}`,
    '',
  ].join('\n');
}

/**
 * Uncomments a commented-out block: its header and every commented line under it, up to the first line that is not.
 *
 * One `#` and at most one space after it are removed, which turns `#   secret: x` into `   secret: x` and leaves a
 * nested `#   # Use the same value` as the comment `  # Use the same value` it was written as.
 */
function uncommentBlock(lines: readonly string[], header: number): string[] {
  const result = [...lines];

  for (let index = header; index < result.length; index += 1) {
    const line = result[index];

    if (!line.startsWith('#')) {
      break;
    }

    result[index] = line.replace(/^#[^\S\n]?/u, '');
  }

  return result;
}

/**
 * Sets `secret` inside the section whose header is at `header`, replacing the key whether it is live or commented out,
 * and inserting it when the section does not mention it at all.
 */
function fillSectionSecret(
  lines: readonly string[],
  header: number,
  secret: string,
): string[] {
  const result = [...lines];
  const end = sectionEnd(result, header);

  for (let index = header + 1; index < end; index += 1) {
    const match = /^(\s+)(?:#\s*)?secret\s*:/u.exec(result[index]);

    if (match) {
      result[index] = `${match[1]}secret: ${yamlString(secret)}`;
      return result;
    }
  }

  result.splice(
    header + 1,
    0,
    `${childIndent(result, header, end)}secret: ${yamlString(secret)}`,
  );

  return result;
}

/**
 * The line after the last one belonging to the section. A top-level key or a top-level comment starts at column zero,
 * so anything indented or blank is still inside.
 */
function sectionEnd(lines: readonly string[], header: number): number {
  for (let index = header + 1; index < lines.length; index += 1) {
    const line = lines[index];

    if (line.trim() !== '' && !/^\s/u.test(line)) {
      return index;
    }
  }

  return lines.length;
}

/** Indentation the section's existing keys use, so an inserted one lines up with them. */
function childIndent(
  lines: readonly string[],
  header: number,
  end: number,
): string {
  for (let index = header + 1; index < end; index += 1) {
    const match = /^(\s+)\S/u.exec(lines[index]);

    if (match) {
      return match[1];
    }
  }

  return DEFAULT_INDENT;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}
