import { randomBytes } from 'node:crypto';
import type { DatabaseConfig } from './database.ts';

export function generateAuthSecret(): string {
  return randomBytes(32).toString('base64url');
}

export interface BuildConfigFileOptions {
  readonly database: DatabaseConfig;
  readonly secret?: string;
}

export function buildConfigFile(options: BuildConfigFileOptions): string {
  const database = options.database;
  const secret = options.secret ?? generateAuthSecret();
  const connection = [`      dialect: ${database.dialect}`];

  if (database.dialect === 'oracle') {
    connection.push(`      serviceName: ${yamlString(database.serviceName)}`);
  } else {
    connection.push(`      database: ${yamlString(database.database)}`);
  }

  if (database.dialect !== 'sqlite') {
    connection.push(
      `      host: ${yamlString(database.host)}`,
      `      port: ${database.port}`,
      `      username: ${yamlString(database.username)}`,
      `      password: ${yamlString(database.password)}`,
    );
  }
  if (database.dialect === 'postgres') {
    connection.push(
      `      schema: [${yamlString(database.schema)}]`,
      `      ssl: ${database.ssl}`,
    );
  }
  if (database.dialect === 'mysql') {
    connection.push(`      charset: ${yamlString(database.charset)}`);
  }

  return [
    '# Generated by @nocobase/create-app.',
    'auth:',
    `  secret: ${yamlString(secret)}`,
    '  emailAndPassword:',
    '    enabled: true',
    '    autoSignIn: false',
    '  session:',
    '    storeSessionInDatabase: true',
    'session:',
    `  secret: ${yamlString(secret)}`,
    'database:',
    '  default: main',
    '  connections:',
    '    main:',
    ...connection,
    '  migrations:',
    '    autoRun: true',
    '  seeds:',
    '    autoRun: true',
    'snowflake:',
    '  workerId: 0',
    '  epoch: 1605024000',
    '',
  ].join('\n');
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}
