import { randomBytes } from 'node:crypto';

export function generateAuthSecret(): string {
  return randomBytes(32).toString('base64url');
}

export interface BuildHubEnvFileOptions {
  authSecret?: string;
}

export function buildHubEnvFile(options: BuildHubEnvFileOptions = {}): string {
  const authSecret = options.authSecret ?? generateAuthSecret();

  return [
    '# Generated by @nocobase/create-hub.',
    'APP_NAME=hub',
    'APP_BASE_PATH=/hub',
    'APP_SERVER_HOST=127.0.0.1',
    'APP_SERVER_PORT=13000',
    '',
    'APP_HOST_BIND=127.0.0.1',
    'APP_HOST_PORT=3000',
    '',
    `AUTH_SECRET=${authSecret}`,
    'HUB_DATABASE_PATH=.nocobase/hub.sqlite',
    'HUB_RELEASE_ROOT=app-dist',
    'APP_PUBLIC_ORIGIN=http://127.0.0.1:3000',
    '',
  ].join('\n');
}
