import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { buildConfigFile, generateAuthSecret } from '../src/lib/config-file.js';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);

/**
 * The real example from the default template, so the placeholders this module rewrites are tested against the file it
 * will actually be handed rather than against a fixture that can quietly diverge from it.
 */
async function readDefaultTemplateExample(): Promise<string> {
  return readFile(
    path.join(
      packageRoot,
      '../../templates/app-template-default/config.example.yml',
    ),
    'utf8',
  );
}

describe('buildConfigFile', () => {
  it('fills in both secrets in the template example', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
      secret: 'test-secret',
    });

    expect(config).toMatch(/^auth:\n(?:\s+#.*\n)*\s+secret: "test-secret"$/mu);
    expect(config).toMatch(
      /^session:\n(?:\s+#.*\n)*\s+secret: "test-secret"$/mu,
    );
    expect(config).not.toContain('replace-with-a-unique-secret');
  });

  /** The example is the only documentation of what an application can be configured with, so none of it is dropped. */
  it('keeps the rest of the example, comments included', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
      secret: 'test-secret',
    });

    expect(config).toContain('# Values under client are public');
    expect(config).toContain('notification:');
    expect(config).toContain('    title: NocoBase');
    expect(config).toContain('  workerId: 0');
  });

  it('replaces the example instruction with a generated header', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
      secret: 'test-secret',
    });

    expect(config.split('\n')[0]).toBe(
      '# Generated by nocobase app config init.',
    );
    expect(config).not.toContain('Copy this file to config.yml');
  });

  /** A commented-out section has to end up live, and its explanatory comments have to survive the uncommenting. */
  it('uncomments a section rather than appending a duplicate key', () => {
    const config = buildConfigFile({
      example: [
        '# Copy this file to config.yml before starting.',
        '# session:',
        '#   # Use the same generated value as auth.secret.',
        '#   secret: replace-with-a-unique-secret',
        '',
        'auth:',
        '  secret: replace-with-a-unique-secret',
      ].join('\n'),
      secret: 'test-secret',
    });

    expect(config).toContain('session:\n');
    expect(config).toContain(
      '  # Use the same generated value as auth.secret.',
    );
    expect(config).toContain('  secret: "test-secret"');
    expect(config.match(/^session:/gmu)).toHaveLength(1);
  });

  it('adds a section the example never mentions', () => {
    const config = buildConfigFile({
      example: 'client:\n  app:\n    title: X\n',
      secret: 's',
    });

    expect(config).toMatch(/^auth:\n {2}secret: "s"$/mu);
    expect(config).toMatch(/^session:\n {2}secret: "s"$/mu);
  });

  it('still produces the secrets when there is no example at all', () => {
    const config = buildConfigFile({ secret: 'test-secret' });

    expect(config).toContain('auth:');
    expect(config).toContain('session:');
    expect(config).toContain('secret: "test-secret"');
  });
});

describe('generateAuthSecret', () => {
  it('produces a distinct URL-safe secret each time', () => {
    const first = generateAuthSecret();
    const second = generateAuthSecret();

    expect(first).not.toBe(second);
    expect(first).toMatch(/^[\w-]+$/u);
    expect(first.length).toBeGreaterThanOrEqual(43);
  });
});
