// @vitest-environment node
import fs from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createDatabaseManager, type DatabaseManager, type Row } from '@nocobase/database';
import { createQueueManager, createSyncQueueConfig, type NocoBaseQueueManager } from '@nocobase/queue';
import { buildWorkflowArtifact, createWorkflowCollections, writeWorkflowArtifact, WORKFLOW_COLLECTIONS } from '@nocobase/workflow';
import { createAppWorkflowRuntime, getWorkflowEngine, isAppWorkflowRuntimeStarted } from '../../server/workflows/runtime.ts';

const roots: string[] = []; const databases: DatabaseManager[] = []; const queues: NocoBaseQueueManager[] = [];
afterEach(async () => { await Promise.all(queues.splice(0).map((queue) => queue.close())); await Promise.all(databases.splice(0).map((database) => database.destroy())); await Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))); });
async function fixture(): Promise<{ root: string; distRoot: string; storeRoot: string; database: DatabaseManager; queue: NocoBaseQueueManager }> { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'app-workflow-startup-')); roots.push(root); const database = createDatabaseManager({ connections: { main: { dialect: 'sqlite', filename: ':memory:' } } }); databases.push(database); await createWorkflowCollections(database.builder()); const queue = createQueueManager(createSyncQueueConfig()); queues.push(queue); return { root, distRoot: path.join(root, 'dist/server/workflows'), storeRoot: path.join(root, 'storage/private'), database, queue }; }
async function emit(distRoot: string, title: string): Promise<string> { const node = { key: 'run', title: 'Run', type: 'run', config: { script: './server/run.ts' }, upstreamKey: null, downstreamKey: null, branchKey: null }; const flatIr = { title, contextSchema: { type: 'object' as const }, start: 'run', nodes: [node] }; const built = buildWorkflowArtifact({ scanned: { key: 'sample', root: '/ci/source', entries: [] }, definition: { title, contextSchema: flatIr.contextSchema, nodes: [] }, flatIr, serverEntries: { one: { source: './server/run.ts', output: 'server/run/one.cjs', exports: ['run'] } }, serverEntryFiles: new Map([['server/run/one.cjs', `exports.run=()=>(${JSON.stringify(title)})`]]) }); await writeWorkflowArtifact(built, distRoot); return built.digest; }
function runtime(f: Awaited<ReturnType<typeof fixture>>) { return createAppWorkflowRuntime({ database: f.database, queue: f.queue, sourceRoot: path.join(f.root, 'server/workflows'), distRoot: f.distRoot, artifactDisk: { driver: 'fs', location: f.storeRoot, visibility: 'private' }, production: true, sourceResolverDiagnostic: false }); }
describe('application workflow Artifact startup', () => {
  it('imports, activates, executes, no-ops on restart, replaces without a run, and mints after a run', async () => { const f = await fixture(); const v1 = await emit(f.distRoot, 'v1'); const firstRuntime = runtime(f); await firstRuntime.start(); expect(isAppWorkflowRuntimeStarted(firstRuntime)).toBe(true); const first = await f.database.query().selectFrom(WORKFLOW_COLLECTIONS.workflows).selectAll().where('key', '=', 'sample').executeTakeFirstOrThrow<Row>(); expect(first.hash).toBe(v1); expect(await fs.readdir(path.join(f.storeRoot, 'workflows/sample', v1))).toEqual(expect.arrayContaining(['workflow.json', 'server'])); await firstRuntime.stop(); const secondRuntime = runtime(f); await secondRuntime.start(); expect(await f.database.query().selectFrom(WORKFLOW_COLLECTIONS.workflows).select('id').where('key', '=', 'sample').execute<Row>()).toHaveLength(1); await secondRuntime.stop(); const v2 = await emit(f.distRoot, 'v2'); const replaceRuntime = runtime(f); await replaceRuntime.start(); const replaced = await f.database.query().selectFrom(WORKFLOW_COLLECTIONS.workflows).selectAll().where('key', '=', 'sample').executeTakeFirstOrThrow<Row>(); expect(replaced.id).toBe(first.id); expect(replaced.hash).toBe(v2); await f.database.query().updateTable(WORKFLOW_COLLECTIONS.workflows).set({ enabled: true }).where('id', '=', replaced.id).execute(); await getWorkflowEngine(replaceRuntime).trigger('sample', {}, { eventKey: 'artifact-run' }); const run = await f.database.query().selectFrom(WORKFLOW_COLLECTIONS.runs).selectAll().where('eventKey', '=', 'artifact-run').executeTakeFirstOrThrow<Row>(); expect(run.hash).toBe(v2); const nodeRun = await f.database.query().selectFrom(WORKFLOW_COLLECTIONS.nodeRuns).select(['result']).where('workflowRunId', '=', run.id).executeTakeFirstOrThrow<Row>(); expect(JSON.parse(String(nodeRun.result))).toBe('v2'); await replaceRuntime.stop(); const v3 = await emit(f.distRoot, 'v3'); const mintRuntime = runtime(f); await mintRuntime.start(); const revisions = await f.database.query().selectFrom(WORKFLOW_COLLECTIONS.workflows).selectAll().where('key', '=', 'sample').orderBy('id').execute<Row>(); expect(revisions).toHaveLength(2); expect(revisions[1].hash).toBe(v3); expect(run.hash).toBe(v2); await mintRuntime.stop(); });
  it('rejects missing/tampered/multiple dist Artifacts before Runtime becomes ready and forbids production source diagnostics', async () => { const f = await fixture(); const missing = runtime(f); await expect(missing.start()).rejects.toThrow(/dist Artifact root/); expect(isAppWorkflowRuntimeStarted(missing)).toBe(false); await missing.stop(); const digest = await emit(f.distRoot, 'bad'); await fs.writeFile(path.join(f.distRoot, 'sample', digest, 'workflow.json'), '{}'); const tampered = runtime(f); await expect(tampered.start()).rejects.toThrow(/sample.*failed startup synchronization/); expect(isAppWorkflowRuntimeStarted(tampered)).toBe(false); await tampered.stop(); await fs.mkdir(path.join(f.distRoot, 'sample', 'a'.repeat(64)), { recursive: true }); const multiple = runtime(f); await expect(multiple.start()).rejects.toThrow(/exactly one digest/); await multiple.stop(); expect(() => createAppWorkflowRuntime({ database: f.database, queue: f.queue, distRoot: f.distRoot, artifactDisk: { driver: 'fs', location: f.storeRoot, visibility: 'private' }, production: true, sourceResolverDiagnostic: true })).toThrow(/forbidden in production/); });
});
