import { AlertCircle, X } from 'lucide-react';
import { Badge } from '../../components/ui/badge.js';
import {
  Alert,
  AlertDescription,
  AlertTitle,
} from '../../components/ui/alert.js';
import { Avatar, AvatarFallback } from '../../components/ui/avatar.js';
import { Button } from '../../components/ui/button.js';
import {
  Dialog as UiDialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '../../components/ui/dialog.js';
import {
  Empty as ShadcnEmpty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from '../../components/ui/empty.js';
import { useTranslation } from '@nocobase/i18n/client';
import { type ReactElement, type ReactNode } from 'react';
import {
  appStatusLabel,
  initials,
  type ReadableError,
  stateLabel,
  type AppActionReason,
  type AppManagementStatus,
} from './utils.js';

export function AppDialog({
  title,
  description,
  onClose,
  children,
  wide = false,
}: {
  readonly title: string;
  readonly description: string;
  readonly onClose: () => void;
  readonly children: ReactNode;
  readonly wide?: boolean;
}): ReactElement {
  return (
    <UiDialog open onOpenChange={(open) => (!open ? onClose() : undefined)}>
      <DialogContent
        className={wide ? 'max-w-none p-8' : 'max-w-xl p-8'}
        style={wide ? { width: 'min(72rem, calc(100vw - 2rem))' } : undefined}
      >
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        {children}
      </DialogContent>
    </UiDialog>
  );
}

export function ErrorBanner({
  error,
  message,
  onClose,
}: {
  readonly error?: ReadableError;
  readonly message?: string;
  readonly onClose?: () => void;
}): ReactElement {
  const { t } = useTranslation('@nocobase/app-plugin-hub');
  const isInvalidArtifact = error?.code === 'INVALID_ARTIFACT';
  const isArtifactVersionMismatch = error?.code === 'ARTIFACT_VERSION_MISMATCH';
  const isForbidden = error?.code === 'FORBIDDEN' || error?.status === 403;
  const isNotFound = error?.code === 'NOT_FOUND' || error?.status === 404;
  const title = isInvalidArtifact
    ? t('errors.invalidArtifactTitle', {
        defaultValue: 'Release artifact could not be uploaded',
      })
    : isArtifactVersionMismatch
      ? t('errors.artifactVersionMismatchTitle', {
          defaultValue: 'Release does not match this application',
        })
      : isForbidden
        ? t('errors.forbiddenTitle', {
            defaultValue: 'You do not have permission to perform this action',
          })
        : isNotFound
          ? t('errors.notFoundTitle', {
              defaultValue: 'The requested resource was not found',
            })
          : error
            ? t('errors.unexpectedTitle', {
                defaultValue: 'Something went wrong',
              })
            : undefined;
  const description = isInvalidArtifact
    ? t('errors.invalidArtifactDescription', {
        defaultValue:
          'Please upload a .tar.gz file generated by pnpm build --tar. The artifact must include dist/package.json and dist/server/embedded.js.',
      })
    : isArtifactVersionMismatch
      ? t('errors.artifactVersionMismatchDescription', {
          defaultValue:
            'Build the release from this application source, then upload the generated artifact again.',
        })
      : isForbidden
        ? t('errors.forbiddenDescription', {
            defaultValue:
              'Your account does not have permission to complete this action.',
          })
        : isNotFound
          ? t('errors.notFoundDescription', {
              defaultValue:
                'The requested application or release is no longer available.',
            })
          : error && !error.isTechnical
            ? error.message
            : t('errors.unexpectedDescription', {
                defaultValue:
                  'The operation could not be completed. Try again. If the problem continues, share the technical details with an administrator.',
              });
  const technicalMessage =
    error &&
    (error.isTechnical || error.technicalMessage !== error.message) &&
    error.technicalMessage !== description
      ? error.technicalMessage
      : undefined;
  return (
    <Alert className='mb-5 border-destructive/30 bg-destructive/5 text-destructive'>
      <AlertCircle className='size-4 shrink-0' />
      <AlertDescription className='min-w-0 text-destructive'>
        {title ? (
          <AlertTitle className='text-destructive'>{title}</AlertTitle>
        ) : null}
        <p className={title ? 'mt-1' : undefined}>{message ?? description}</p>
        {technicalMessage ? (
          <details className='mt-2 text-xs text-destructive/80'>
            <summary className='cursor-pointer select-none'>
              {t('errors.showTechnicalDetails', {
                defaultValue: 'Show technical details',
              })}
            </summary>
            <pre className='mt-2 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md bg-destructive/10 p-2 font-mono leading-5'>
              {error?.code
                ? `${t('errors.code', {
                    code: error.code,
                    defaultValue: `Error code: ${error.code}`,
                  })}\n${technicalMessage}`
                : technicalMessage}
            </pre>
          </details>
        ) : null}
      </AlertDescription>
      {onClose ? (
        <Button
          aria-label={t('common.dismissError', {
            defaultValue: 'Dismiss error',
          })}
          className='absolute top-1 right-1'
          onClick={onClose}
          size='icon'
          variant='ghost'
        >
          <X className='size-4' />
        </Button>
      ) : null}
    </Alert>
  );
}

export function Field({
  label,
  hint,
  children,
}: {
  readonly label: string;
  readonly hint?: string;
  readonly children: ReactNode;
}): ReactElement {
  return (
    <label className='mb-4 block text-sm font-medium'>
      {label}
      <span className='mt-2 block'>{children}</span>
      {hint ? (
        <span className='mt-1.5 block text-xs font-normal text-muted-foreground'>
          {hint}
        </span>
      ) : null}
    </label>
  );
}

export function Empty({
  icon,
  title,
  description,
  action,
}: {
  readonly icon: ReactNode;
  readonly title: string;
  readonly description?: string;
  readonly action?: ReactNode;
}): ReactElement {
  return (
    <ShadcnEmpty className='bg-card'>
      <EmptyMedia>{icon}</EmptyMedia>
      <EmptyHeader>
        <EmptyTitle>{title}</EmptyTitle>
        {description ? (
          <EmptyDescription>{description}</EmptyDescription>
        ) : null}
      </EmptyHeader>
      {action ? <EmptyContent>{action}</EmptyContent> : null}
    </ShadcnEmpty>
  );
}

export function ViewButton({
  active,
  label,
  onClick,
  icon,
}: {
  readonly active: boolean;
  readonly label: string;
  readonly onClick: () => void;
  readonly icon: ReactNode;
}): ReactElement {
  return (
    <Button
      aria-label={label}
      onClick={onClick}
      className={active ? 'size-8 bg-muted' : 'size-8 text-muted-foreground'}
      size='icon'
      variant='ghost'
    >
      {icon}
    </Button>
  );
}

export function AppMark({
  name,
  small = false,
}: {
  readonly name: string;
  readonly small?: boolean;
}): ReactElement {
  return (
    <Avatar className={small ? 'size-9' : 'size-12'}>
      <AvatarFallback className='bg-primary/10 font-semibold text-primary'>
        {initials(name)}
      </AvatarFallback>
    </Avatar>
  );
}

export function StatusBadge({
  state,
}: {
  readonly state: string;
}): ReactElement {
  const { t } = useTranslation('@nocobase/app-plugin-hub');
  const statusKeys: Readonly<Record<string, string>> = {
    'host-unavailable': 'status.hostUnavailable',
    'deployment-pending': 'status.deploymentPending',
    'not-deployed': 'status.notDeployed',
    ready: 'status.ready',
    stopped: 'status.stopped',
    unknown: 'status.unknown',
    failed: 'status.failed',
    running: 'status.running',
  };
  const statusKey = statusKeys[state];
  const label =
    statusKey && state in statusKeys
      ? t(statusKey, {
          defaultValue: appStatusLabel(state as AppManagementStatus),
        })
      : stateLabel(state);
  const style =
    state === 'running'
      ? 'bg-emerald-500/10 text-emerald-700'
      : state === 'failed'
        ? 'bg-destructive/10 text-destructive'
        : state === 'pending' ||
            state === 'queued' ||
            state === 'deploying' ||
            state === 'deployment-pending'
          ? 'bg-amber-500/10 text-amber-700'
          : state === 'succeeded'
            ? 'bg-emerald-500/10 text-emerald-700'
            : state === 'stopped' || state === 'ready'
              ? 'bg-sky-500/10 text-sky-700'
              : 'bg-muted text-muted-foreground';
  return (
    <Badge className={`self-center gap-1.5 whitespace-nowrap ${style}`}>
      <span
        className={`size-1.5 rounded-full ${state === 'running' || state === 'succeeded' ? 'bg-emerald-500' : state === 'failed' ? 'bg-destructive' : state === 'pending' || state === 'queued' || state === 'deploying' || state === 'deployment-pending' ? 'bg-amber-500' : state === 'stopped' || state === 'ready' ? 'bg-sky-500' : 'bg-neutral-400'}`}
      />
      {label}
    </Badge>
  );
}

export function ActionAvailabilityHint({
  action,
  reason,
}: {
  readonly action:
    'start' | 'stop' | 'restart' | 'deploy' | 'rollback' | 'visit';
  readonly reason?: AppActionReason;
}): ReactElement | null {
  const { t } = useTranslation('@nocobase/app-plugin-hub');
  if (!reason) return null;
  const actionLabel: Readonly<Record<typeof action, string>> = {
    start: t('detail.start', { defaultValue: 'Start' }),
    stop: t('detail.stop', { defaultValue: 'Stop' }),
    restart: t('detail.restart', { defaultValue: 'Restart' }),
    deploy: t('deployments.deploy', { defaultValue: 'Deploy' }),
    rollback: t('deployments.rollback', { defaultValue: 'Roll back' }),
    visit: t('detail.visit', { defaultValue: 'Visit' }),
  };
  const reasonLabel = t(`actions.${reason}`, {
    defaultValue: reason,
  });
  return (
    <p className='text-xs text-muted-foreground' role='status'>
      {t(`actions.${action}Unavailable`, {
        defaultValue: `${actionLabel[action]} unavailable: ${reasonLabel}`,
        reason: reasonLabel,
      })}
    </p>
  );
}
