import { randomBytes } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import type { ConfigPaths } from '@nocobase/app-server/config';

export type InstallDatabaseDialect = 'sqlite' | 'postgres' | 'mysql';

export interface InstallDatabaseConfigInput {
  readonly dialect: InstallDatabaseDialect;
  readonly database: string;
  readonly debug?: boolean;
  readonly host?: string;
  readonly port?: number;
  readonly username?: string;
  readonly password?: string;
  readonly schema?: string;
  readonly ssl?: boolean;
  readonly charset?: string;
}

export interface ConfigureInstallationOptions {
  readonly paths: ConfigPaths;
  readonly generateSecret?: () => string;
}

export interface ConfigureInstallationResult {
  readonly configured: true;
  readonly restartRequired: true;
}

type InstallConfigurationErrorStatus = 400 | 409 | 500;

export class InstallConfigurationError extends Error {
  public readonly status: InstallConfigurationErrorStatus;

  public constructor(status: InstallConfigurationErrorStatus, message: string) {
    super(message);
    this.name = 'InstallConfigurationError';
    this.status = status;
  }
}

export async function configureInstallation(
  input: unknown,
  options: ConfigureInstallationOptions,
): Promise<ConfigureInstallationResult> {
  const config = parseInstallDatabaseConfig(input);
  const configPath = options.paths.root('config.yml');

  const generateSecret =
    options.generateSecret ?? (() => randomBytes(32).toString('base64url'));
  const secret = generateSecret();
  assertSafeString(secret, 'Generated authentication secret', false);

  const contents = buildYamlConfiguration(config, secret);

  try {
    await writeFile(configPath, contents, {
      encoding: 'utf8',
      flag: 'wx',
      mode: 0o600,
    });
  } catch (error) {
    if (isNodeError(error) && error.code === 'EEXIST') {
      throw new InstallConfigurationError(
        409,
        'The application has already been configured.',
      );
    }

    throw new InstallConfigurationError(500, 'Unable to create config.yml.');
  }

  return { configured: true, restartRequired: true };
}

function buildYamlConfiguration(
  config: InstallDatabaseConfigInput,
  secret: string,
): string {
  const lines = [
    '# Generated by @nocobase/app-plugin-install.',
    'auth:',
    `  secret: ${JSON.stringify(secret)}`,
    'session:',
    `  secret: ${JSON.stringify(secret)}`,
    'database:',
    '  default: main',
    '  connections:',
    '    main:',
    `      dialect: ${config.dialect}`,
    `      database: ${JSON.stringify(config.database)}`,
  ];
  if (config.dialect !== 'sqlite') {
    lines.push(
      `      host: ${JSON.stringify(config.host)}`,
      `      port: ${config.port}`,
      `      username: ${JSON.stringify(config.username)}`,
      `      password: ${JSON.stringify(config.password ?? '')}`,
    );
  }
  if (config.dialect === 'postgres') {
    lines.push(
      `      schema: [${JSON.stringify(config.schema)}]`,
      `      ssl: ${config.ssl ?? false}`,
    );
  }
  if (config.dialect === 'mysql') {
    lines.push(`      charset: ${JSON.stringify(config.charset)}`);
  }
  lines.push(`      debug: ${config.debug ?? false}`);
  lines.push(
    '  migrations:',
    '    autoRun: true',
    '  seeds:',
    '    autoRun: true',
    '',
  );
  return lines.join('\n');
}

export function parseInstallDatabaseConfig(
  input: unknown,
): InstallDatabaseConfigInput {
  if (!isRecord(input)) {
    throw invalidInput('The request body must be a JSON object.');
  }

  const dialect = input.dialect;
  if (dialect !== 'sqlite' && dialect !== 'postgres' && dialect !== 'mysql') {
    throw invalidInput(
      'Database dialect must be "sqlite", "postgres", or "mysql".',
    );
  }

  const database = readRequiredString(input, 'database', 'Database');
  const debug = readBoolean(input, 'debug', false);

  if (dialect === 'sqlite') {
    return { dialect, database, debug };
  }

  const host = readRequiredString(input, 'host', 'Database host');
  const port = readPort(input);
  const username = readRequiredString(input, 'username', 'Database username');
  const password = readOptionalString(input, 'password', 'Database password');

  if (dialect === 'mysql') {
    return {
      dialect,
      host,
      port,
      database,
      username,
      password,
      charset: readRequiredString(input, 'charset', 'Database charset'),
      debug,
    };
  }

  return {
    dialect,
    host,
    port,
    database,
    username,
    password,
    schema: readRequiredString(input, 'schema', 'Database schema'),
    ssl: readBoolean(input, 'ssl', false),
    debug,
  };
}

function readRequiredString(
  input: Readonly<Record<string, unknown>>,
  key: string,
  label: string,
): string {
  const value = input[key];
  if (typeof value !== 'string') {
    throw invalidInput(`${label} must be a string.`);
  }

  assertSafeString(value, label, false);
  if (value.trim() === '') {
    throw invalidInput(`${label} is required.`);
  }

  return value.trim();
}

function readOptionalString(
  input: Readonly<Record<string, unknown>>,
  key: string,
  label: string,
): string {
  const value = input[key];
  if (value === undefined) {
    return '';
  }
  if (typeof value !== 'string') {
    throw invalidInput(`${label} must be a string.`);
  }

  assertSafeString(value, label, true);
  return value;
}

function readBoolean(
  input: Readonly<Record<string, unknown>>,
  key: string,
  defaultValue: boolean,
): boolean {
  const value = input[key];
  if (value === undefined) {
    return defaultValue;
  }
  if (typeof value !== 'boolean') {
    throw invalidInput(`${key} must be a boolean.`);
  }
  return value;
}

function readPort(input: Readonly<Record<string, unknown>>): number {
  const value = input.port;
  if (
    typeof value !== 'number' ||
    !Number.isInteger(value) ||
    value < 1 ||
    value > 65_535
  ) {
    throw invalidInput('Database port must be an integer from 1 to 65535.');
  }
  return value;
}

function assertSafeString(
  value: string,
  label: string,
  allowEmpty: boolean,
): void {
  if (!allowEmpty && value.length === 0) {
    throw invalidInput(`${label} is required.`);
  }
  if (/[\0\r\n]/u.test(value)) {
    throw invalidInput(`${label} must not contain line breaks or null bytes.`);
  }
}

function invalidInput(message: string): InstallConfigurationError {
  return new InstallConfigurationError(400, message);
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error;
}
