import { useEffect, useState } from 'react';
import { workflowApi } from './data';
import type { WorkflowNodeRunPayload, WorkflowNodeRunRecord } from './types';

export interface WorkflowInspectorProps { nodeKey: string | null; attempts: readonly WorkflowNodeRunRecord[]; selectedAttempt?: string | null; onSelectAttempt?: (id: string) => void; }
export function WorkflowInspector({ nodeKey, attempts, selectedAttempt, onSelectAttempt }: WorkflowInspectorProps) { if (!nodeKey) return <aside aria-label="Workflow inspector"><h2>Workflow overview</h2><p>Select a node to inspect it.</p></aside>; return <aside aria-label="Workflow inspector"><h2>{nodeKey}</h2><label>Attempt <select value={selectedAttempt ?? attempts.at(-1)?.id ?? ''} onChange={(event) => onSelectAttempt?.(event.target.value)}>{attempts.map((attempt, index) => <option key={attempt.id} value={attempt.id}>{index + 1} · {attempt.status}</option>)}</select></label><ol>{attempts.map((attempt) => <li key={attempt.id}>#{attempt.id} · {attempt.startedAt} → {attempt.finishedAt ?? 'running'}</li>)}</ol></aside>; }

function displayValue(value: unknown): string { if (value === undefined) return 'undefined'; if (typeof value === 'string') return value; try { return JSON.stringify(value, null, 2); } catch { return String(value); } }
function formatClientTime(value: string | null): string { if (!value) return 'running'; const date = new Date(value); const part = (next: number, width: number = 2): string => String(next).padStart(width, '0'); return `${date.getFullYear()}-${part(date.getMonth() + 1)}-${part(date.getDate())} ${part(date.getHours())}:${part(date.getMinutes())}:${part(date.getSeconds())}.${part(date.getMilliseconds(), 3)}`; }
function runStatusLabel(status: number): string { return status === 1 ? 'Succeeded' : status === 0 ? 'Running' : status === -1 ? 'Failed' : status === -2 ? 'Error' : 'Aborted'; }
function useAnimatedDialogClose(onClose: () => void): { closing: boolean; close: () => void } { const [closing, setClosing] = useState(false); const close = (): void => { if (closing) return; if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { onClose(); return; } setClosing(true); window.setTimeout(onClose, 160); }; return { closing, close }; }
export interface WorkflowRunResultDialogProps { runId: string; nodeRun: WorkflowNodeRunRecord; nodeTitle?: string; onClose: () => void; }
export function WorkflowRunResultDialog({ runId, nodeRun, nodeTitle, onClose }: WorkflowRunResultDialogProps) {
  const [attemptId, setAttemptId] = useState(nodeRun.id); const [attempts, setAttempts] = useState<WorkflowNodeRunRecord[]>([nodeRun]); const [payload, setPayload] = useState<WorkflowNodeRunPayload | null>(null); const [error, setError] = useState<string | null>(null);
  const animatedClose = useAnimatedDialogClose(onClose);
  useEffect(() => { setAttemptId(nodeRun.id); }, [nodeRun.id]);
  useEffect(() => { let active = true; setAttempts([nodeRun]); void workflowApi.nodeRuns(runId, nodeRun.nodeKey).then((next) => { if (active) setAttempts(next); }, () => { /* The latest summary remains enough to display the selected run. */ }); return () => { active = false; }; }, [nodeRun.id, nodeRun.nodeKey, runId]);
  useEffect(() => { let active = true; setPayload(null); setError(null); void workflowApi.payload(runId, attemptId).then((next) => { if (active) setPayload(next); }, (cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : String(cause)); }); return () => { active = false; }; }, [attemptId, runId]);
  const current = attempts.find((attempt) => attempt.id === attemptId) ?? nodeRun;
  return <div className={animatedClose.closing ? 'workflow-result-backdrop closing' : 'workflow-result-backdrop'} role="presentation" onMouseDown={animatedClose.close}><section className="workflow-result-dialog" role="dialog" aria-modal="true" aria-labelledby="workflow-result-title" onMouseDown={(event) => event.stopPropagation()}><header><div><h2 id="workflow-result-title">{nodeTitle ?? current.nodeKey}</h2><p>{runStatusLabel(current.status)} · {formatClientTime(current.startedAt)} → {formatClientTime(current.finishedAt)}</p></div><button type="button" aria-label="Close result" onClick={animatedClose.close}>×</button></header>{attempts.length > 1 ? <label>Attempt <select value={attemptId} onChange={(event) => setAttemptId(event.target.value)}>{attempts.map((attempt, index) => <option key={attempt.id} value={attempt.id}>{index + 1} · {runStatusLabel(attempt.status)} · {formatClientTime(attempt.startedAt)}</option>)}</select></label> : null}{error ? <p role="alert">{error}</p> : payload ? <div className="workflow-result-content">{payload.truncated ? <p role="status">Large payload was truncated for display.</p> : null}{payload.error ? <><h3>Error</h3><pre>{payload.error}</pre></> : <><h3>Result</h3><pre>{displayValue(payload.result)}</pre></>}{payload.log?.trim() ? <><h3>Log</h3><pre>{payload.log}</pre></> : null}</div> : <p>Loading result…</p>}</section></div>;
}

export interface WorkflowContextDialogProps { context: unknown; onClose: () => void; }
export function WorkflowContextDialog({ context, onClose }: WorkflowContextDialogProps) { const animatedClose = useAnimatedDialogClose(onClose); return <div className={animatedClose.closing ? 'workflow-result-backdrop closing' : 'workflow-result-backdrop'} role="presentation" onMouseDown={animatedClose.close}><section className="workflow-result-dialog" role="dialog" aria-modal="true" aria-labelledby="workflow-context-title" onMouseDown={(event) => event.stopPropagation()}><header><div><h2 id="workflow-context-title">Workflow context</h2><p>Input context available when this execution started.</p></div><button type="button" aria-label="Close context" onClick={animatedClose.close}>×</button></header><div className="workflow-result-content"><h3>Context</h3><pre>{displayValue(context)}</pre></div></section></div>; }
