import { Blocks, Home, LayoutTemplate, ShoppingCart } from 'lucide-react';
import {
  defineAppRoutes,
  defineSettingsRoutes,
  type AppClientRouteContribution,
} from '@nocobase/app-client/plugins';

const appRoutes: AppClientRouteContribution = defineAppRoutes([
  {
    // Every signed-in user reaches the landing page. `authz: 'skip'` takes it out of page authorization entirely, so
    // no permission change can leave a user signed in with nowhere to land.
    authz: 'skip',
    auth: 'required',
    componentLoader: () => import('./pages/home.js'),
    name: 'home',
    navigation: { title: 'navigation.home', icon: Home },
    path: '/',
  },

  // Reference pages for building application UI: `Examples` are complete business screens on mock data,
  // `Components` shows one shadcn/ui primitive per page, and both groups share the frame in
  // `client/pages/reference/shared.tsx`. They are application pages like any other: visible to every signed-in user
  // through `authz: 'skip'` and shipped in a production build.
  // The set is filled in page by page, and a route is declared together with the page it loads, never before it: the
  // entries whose page is still to write stay commented out below. Uncomment one, and the lucide-react icon it names,
  // when the page lands.
  {
    name: 'examples',
    auth: 'required',
    navigation: { title: 'examples.title', icon: LayoutTemplate },
    children: [
      // {
      //   name: 'examples-dashboard',
      //   path: '/examples/dashboard',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: {
      //     title: 'examples.dashboard.title',
      //     icon: LayoutDashboard,
      //   },
      //   breadcrumb: { title: 'examples.dashboard.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/dashboard/dashboard.js'),
      // },
      {
        name: 'examples-orders',
        path: '/examples/orders',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'examples.orders.title', icon: ShoppingCart },
        breadcrumb: { title: 'examples.orders.title' },
        componentLoader: () =>
          import('./pages/reference/examples/orders/orders.js'),
      },
      // {
      //   name: 'examples-customers',
      //   path: '/examples/customers',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'examples.customers.title', icon: Users },
      //   breadcrumb: { title: 'examples.customers.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/customers/customers.js'),
      // },
      // {
      //   name: 'examples-product-form',
      //   path: '/examples/product-form',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: {
      //     title: 'examples.productForm.title',
      //     icon: PackagePlus,
      //   },
      //   breadcrumb: { title: 'examples.productForm.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/product-form/product-form.js'),
      // },
      // {
      //   name: 'examples-inbox',
      //   path: '/examples/inbox',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'examples.inbox.title', icon: MessagesSquare },
      //   breadcrumb: { title: 'examples.inbox.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/inbox/inbox.js'),
      // },
      // {
      //   name: 'examples-survey',
      //   path: '/examples/survey',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'examples.survey.title', icon: ClipboardList },
      //   breadcrumb: { title: 'examples.survey.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/survey/survey.js'),
      // },
      // {
      //   name: 'examples-team-settings',
      //   path: '/examples/team-settings',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: {
      //     title: 'examples.teamSettings.title',
      //     icon: Settings2,
      //   },
      //   breadcrumb: { title: 'examples.teamSettings.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/team-settings/team-settings.js'),
      // },
      // {
      //   name: 'examples-schedule',
      //   path: '/examples/schedule',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'examples.schedule.title', icon: CalendarDays },
      //   breadcrumb: { title: 'examples.schedule.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/examples/schedule/schedule.js'),
      // },
    ],
  },
  {
    name: 'components',
    auth: 'required',
    navigation: { title: 'components.title', icon: Blocks },
    children: [
      {
        name: 'components-accordion',
        path: '/components/accordion',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.accordion.title' },
        breadcrumb: { title: 'components.accordion.title' },
        componentLoader: () =>
          import('./pages/reference/components/accordion.js'),
      },
      {
        name: 'components-alert',
        path: '/components/alert',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.alert.title' },
        breadcrumb: { title: 'components.alert.title' },
        componentLoader: () => import('./pages/reference/components/alert.js'),
      },
      {
        name: 'components-alert-dialog',
        path: '/components/alert-dialog',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.alertDialog.title' },
        breadcrumb: { title: 'components.alertDialog.title' },
        componentLoader: () =>
          import('./pages/reference/components/alert-dialog.js'),
      },
      {
        name: 'components-aspect-ratio',
        path: '/components/aspect-ratio',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.aspectRatio.title' },
        breadcrumb: { title: 'components.aspectRatio.title' },
        componentLoader: () =>
          import('./pages/reference/components/aspect-ratio.js'),
      },
      {
        name: 'components-attachment',
        path: '/components/attachment',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.attachment.title' },
        breadcrumb: { title: 'components.attachment.title' },
        componentLoader: () =>
          import('./pages/reference/components/attachment.js'),
      },
      {
        name: 'components-avatar',
        path: '/components/avatar',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.avatar.title' },
        breadcrumb: { title: 'components.avatar.title' },
        componentLoader: () => import('./pages/reference/components/avatar.js'),
      },
      {
        name: 'components-badge',
        path: '/components/badge',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.badge.title' },
        breadcrumb: { title: 'components.badge.title' },
        componentLoader: () => import('./pages/reference/components/badge.js'),
      },
      {
        name: 'components-breadcrumb',
        path: '/components/breadcrumb',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.breadcrumb.title' },
        breadcrumb: { title: 'components.breadcrumb.title' },
        componentLoader: () =>
          import('./pages/reference/components/breadcrumb.js'),
      },
      {
        name: 'components-bubble',
        path: '/components/bubble',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.bubble.title' },
        breadcrumb: { title: 'components.bubble.title' },
        componentLoader: () => import('./pages/reference/components/bubble.js'),
      },
      {
        name: 'components-button',
        path: '/components/button',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.button.title' },
        breadcrumb: { title: 'components.button.title' },
        componentLoader: () => import('./pages/reference/components/button.js'),
      },
      {
        name: 'components-button-group',
        path: '/components/button-group',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.buttonGroup.title' },
        breadcrumb: { title: 'components.buttonGroup.title' },
        componentLoader: () =>
          import('./pages/reference/components/button-group.js'),
      },
      {
        name: 'components-calendar',
        path: '/components/calendar',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.calendar.title' },
        breadcrumb: { title: 'components.calendar.title' },
        componentLoader: () =>
          import('./pages/reference/components/calendar.js'),
      },
      {
        name: 'components-card',
        path: '/components/card',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.card.title' },
        breadcrumb: { title: 'components.card.title' },
        componentLoader: () => import('./pages/reference/components/card.js'),
      },
      {
        name: 'components-carousel',
        path: '/components/carousel',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.carousel.title' },
        breadcrumb: { title: 'components.carousel.title' },
        componentLoader: () =>
          import('./pages/reference/components/carousel.js'),
      },
      {
        name: 'components-chart',
        path: '/components/chart',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.chart.title' },
        breadcrumb: { title: 'components.chart.title' },
        componentLoader: () => import('./pages/reference/components/chart.js'),
      },
      {
        name: 'components-checkbox',
        path: '/components/checkbox',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.checkbox.title' },
        breadcrumb: { title: 'components.checkbox.title' },
        componentLoader: () =>
          import('./pages/reference/components/checkbox.js'),
      },
      {
        name: 'components-collapsible',
        path: '/components/collapsible',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.collapsible.title' },
        breadcrumb: { title: 'components.collapsible.title' },
        componentLoader: () =>
          import('./pages/reference/components/collapsible.js'),
      },
      {
        name: 'components-combobox',
        path: '/components/combobox',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.combobox.title' },
        breadcrumb: { title: 'components.combobox.title' },
        componentLoader: () =>
          import('./pages/reference/components/combobox.js'),
      },
      {
        name: 'components-command',
        path: '/components/command',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.command.title' },
        breadcrumb: { title: 'components.command.title' },
        componentLoader: () =>
          import('./pages/reference/components/command.js'),
      },
      {
        name: 'components-context-menu',
        path: '/components/context-menu',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.contextMenu.title' },
        breadcrumb: { title: 'components.contextMenu.title' },
        componentLoader: () =>
          import('./pages/reference/components/context-menu.js'),
      },
      {
        name: 'components-data-table',
        path: '/components/data-table',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.dataTable.title' },
        breadcrumb: { title: 'components.dataTable.title' },
        componentLoader: () =>
          import('./pages/reference/components/data-table.js'),
      },
      {
        name: 'components-date-picker',
        path: '/components/date-picker',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.datePicker.title' },
        breadcrumb: { title: 'components.datePicker.title' },
        componentLoader: () =>
          import('./pages/reference/components/date-picker.js'),
      },
      {
        name: 'components-dialog',
        path: '/components/dialog',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.dialog.title' },
        breadcrumb: { title: 'components.dialog.title' },
        componentLoader: () => import('./pages/reference/components/dialog.js'),
      },
      // {
      //   name: 'components-direction',
      //   path: '/components/direction',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.direction.title' },
      //   breadcrumb: { title: 'components.direction.title' },
      //   componentLoader: () => import('./pages/reference/components/direction.js'),
      // },
      // {
      //   name: 'components-drawer',
      //   path: '/components/drawer',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.drawer.title' },
      //   breadcrumb: { title: 'components.drawer.title' },
      //   componentLoader: () => import('./pages/reference/components/drawer.js'),
      // },
      // {
      //   name: 'components-dropdown-menu',
      //   path: '/components/dropdown-menu',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.dropdownMenu.title' },
      //   breadcrumb: { title: 'components.dropdownMenu.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/components/dropdown-menu.js'),
      // },
      // {
      //   name: 'components-empty',
      //   path: '/components/empty',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.empty.title' },
      //   breadcrumb: { title: 'components.empty.title' },
      //   componentLoader: () => import('./pages/reference/components/empty.js'),
      // },
      // {
      //   name: 'components-field',
      //   path: '/components/field',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.field.title' },
      //   breadcrumb: { title: 'components.field.title' },
      //   componentLoader: () => import('./pages/reference/components/field.js'),
      // },
      // {
      //   name: 'components-hover-card',
      //   path: '/components/hover-card',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.hoverCard.title' },
      //   breadcrumb: { title: 'components.hoverCard.title' },
      //   componentLoader: () => import('./pages/reference/components/hover-card.js'),
      // },
      // {
      //   name: 'components-input',
      //   path: '/components/input',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.input.title' },
      //   breadcrumb: { title: 'components.input.title' },
      //   componentLoader: () => import('./pages/reference/components/input.js'),
      // },
      // {
      //   name: 'components-input-group',
      //   path: '/components/input-group',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.inputGroup.title' },
      //   breadcrumb: { title: 'components.inputGroup.title' },
      //   componentLoader: () => import('./pages/reference/components/input-group.js'),
      // },
      // {
      //   name: 'components-input-otp',
      //   path: '/components/input-otp',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.inputOtp.title' },
      //   breadcrumb: { title: 'components.inputOtp.title' },
      //   componentLoader: () => import('./pages/reference/components/input-otp.js'),
      // },
      // {
      //   name: 'components-item',
      //   path: '/components/item',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.item.title' },
      //   breadcrumb: { title: 'components.item.title' },
      //   componentLoader: () => import('./pages/reference/components/item.js'),
      // },
      // {
      //   name: 'components-kbd',
      //   path: '/components/kbd',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.kbd.title' },
      //   breadcrumb: { title: 'components.kbd.title' },
      //   componentLoader: () => import('./pages/reference/components/kbd.js'),
      // },
      // {
      //   name: 'components-label',
      //   path: '/components/label',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.label.title' },
      //   breadcrumb: { title: 'components.label.title' },
      //   componentLoader: () => import('./pages/reference/components/label.js'),
      // },
      // {
      //   name: 'components-marker',
      //   path: '/components/marker',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.marker.title' },
      //   breadcrumb: { title: 'components.marker.title' },
      //   componentLoader: () => import('./pages/reference/components/marker.js'),
      // },
      // {
      //   name: 'components-menubar',
      //   path: '/components/menubar',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.menubar.title' },
      //   breadcrumb: { title: 'components.menubar.title' },
      //   componentLoader: () => import('./pages/reference/components/menubar.js'),
      // },
      // {
      //   name: 'components-message',
      //   path: '/components/message',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.message.title' },
      //   breadcrumb: { title: 'components.message.title' },
      //   componentLoader: () => import('./pages/reference/components/message.js'),
      // },
      // {
      //   name: 'components-message-scroller',
      //   path: '/components/message-scroller',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.messageScroller.title' },
      //   breadcrumb: { title: 'components.messageScroller.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/components/message-scroller.js'),
      // },
      // {
      //   name: 'components-native-select',
      //   path: '/components/native-select',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.nativeSelect.title' },
      //   breadcrumb: { title: 'components.nativeSelect.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/components/native-select.js'),
      // },
      // {
      //   name: 'components-navigation-menu',
      //   path: '/components/navigation-menu',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.navigationMenu.title' },
      //   breadcrumb: { title: 'components.navigationMenu.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/components/navigation-menu.js'),
      // },
      // {
      //   name: 'components-pagination',
      //   path: '/components/pagination',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.pagination.title' },
      //   breadcrumb: { title: 'components.pagination.title' },
      //   componentLoader: () => import('./pages/reference/components/pagination.js'),
      // },
      // {
      //   name: 'components-popover',
      //   path: '/components/popover',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.popover.title' },
      //   breadcrumb: { title: 'components.popover.title' },
      //   componentLoader: () => import('./pages/reference/components/popover.js'),
      // },
      // {
      //   name: 'components-progress',
      //   path: '/components/progress',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.progress.title' },
      //   breadcrumb: { title: 'components.progress.title' },
      //   componentLoader: () => import('./pages/reference/components/progress.js'),
      // },
      // {
      //   name: 'components-questionnaire',
      //   path: '/components/questionnaire',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.questionnaire.title' },
      //   breadcrumb: { title: 'components.questionnaire.title' },
      //   componentLoader: () =>
      //     import('./pages/reference/components/questionnaire.js'),
      // },
      // {
      //   name: 'components-radio-group',
      //   path: '/components/radio-group',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.radioGroup.title' },
      //   breadcrumb: { title: 'components.radioGroup.title' },
      //   componentLoader: () => import('./pages/reference/components/radio-group.js'),
      // },
      // {
      //   name: 'components-resizable',
      //   path: '/components/resizable',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.resizable.title' },
      //   breadcrumb: { title: 'components.resizable.title' },
      //   componentLoader: () => import('./pages/reference/components/resizable.js'),
      // },
      // {
      //   name: 'components-scroll-area',
      //   path: '/components/scroll-area',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.scrollArea.title' },
      //   breadcrumb: { title: 'components.scrollArea.title' },
      //   componentLoader: () => import('./pages/reference/components/scroll-area.js'),
      // },
      // {
      //   name: 'components-select',
      //   path: '/components/select',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.select.title' },
      //   breadcrumb: { title: 'components.select.title' },
      //   componentLoader: () => import('./pages/reference/components/select.js'),
      // },
      {
        name: 'components-separator',
        path: '/components/separator',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.separator.title' },
        breadcrumb: { title: 'components.separator.title' },
        componentLoader: () =>
          import('./pages/reference/components/separator.js'),
      },
      {
        name: 'components-sheet',
        path: '/components/sheet',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.sheet.title' },
        breadcrumb: { title: 'components.sheet.title' },
        componentLoader: () => import('./pages/reference/components/sheet.js'),
      },
      {
        name: 'components-sidebar',
        path: '/components/sidebar',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.sidebar.title' },
        breadcrumb: { title: 'components.sidebar.title' },
        componentLoader: () =>
          import('./pages/reference/components/sidebar.js'),
      },
      {
        name: 'components-skeleton',
        path: '/components/skeleton',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.skeleton.title' },
        breadcrumb: { title: 'components.skeleton.title' },
        componentLoader: () =>
          import('./pages/reference/components/skeleton.js'),
      },
      {
        name: 'components-slider',
        path: '/components/slider',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.slider.title' },
        breadcrumb: { title: 'components.slider.title' },
        componentLoader: () => import('./pages/reference/components/slider.js'),
      },
      {
        name: 'components-spinner',
        path: '/components/spinner',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.spinner.title' },
        breadcrumb: { title: 'components.spinner.title' },
        componentLoader: () =>
          import('./pages/reference/components/spinner.js'),
      },
      {
        name: 'components-switch',
        path: '/components/switch',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.switch.title' },
        breadcrumb: { title: 'components.switch.title' },
        componentLoader: () => import('./pages/reference/components/switch.js'),
      },
      {
        name: 'components-table',
        path: '/components/table',
        auth: 'required',
        authz: 'skip',
        navigation: { title: 'components.table.title' },
        breadcrumb: { title: 'components.table.title' },
        componentLoader: () => import('./pages/reference/components/table.js'),
      },
      // {
      //   name: 'components-tabs',
      //   path: '/components/tabs',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.tabs.title' },
      //   breadcrumb: { title: 'components.tabs.title' },
      //   componentLoader: () => import('./pages/reference/components/tabs.js'),
      // },
      // {
      //   name: 'components-textarea',
      //   path: '/components/textarea',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.textarea.title' },
      //   breadcrumb: { title: 'components.textarea.title' },
      //   componentLoader: () => import('./pages/reference/components/textarea.js'),
      // },
      // {
      //   name: 'components-toast',
      //   path: '/components/toast',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.toast.title' },
      //   breadcrumb: { title: 'components.toast.title' },
      //   componentLoader: () => import('./pages/reference/components/toast.js'),
      // },
      // {
      //   name: 'components-toggle',
      //   path: '/components/toggle',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.toggle.title' },
      //   breadcrumb: { title: 'components.toggle.title' },
      //   componentLoader: () => import('./pages/reference/components/toggle.js'),
      // },
      // {
      //   name: 'components-toggle-group',
      //   path: '/components/toggle-group',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.toggleGroup.title' },
      //   breadcrumb: { title: 'components.toggleGroup.title' },
      //   componentLoader: () => import('./pages/reference/components/toggle-group.js'),
      // },
      // {
      //   name: 'components-tooltip',
      //   path: '/components/tooltip',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.tooltip.title' },
      //   breadcrumb: { title: 'components.tooltip.title' },
      //   componentLoader: () => import('./pages/reference/components/tooltip.js'),
      // },
      // {
      //   name: 'components-typography',
      //   path: '/components/typography',
      //   auth: 'required',
      //   authz: 'skip',
      //   navigation: { title: 'components.typography.title' },
      //   breadcrumb: { title: 'components.typography.title' },
      //   componentLoader: () => import('./pages/reference/components/typography.js'),
      // },
    ],
  },

  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/login.js'),
    name: 'login',
    path: '/login',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/register.js'),
    name: 'register',
    path: '/register',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/forgot-password.js'),
    name: 'forgot-password',
    path: '/forgot-password',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/reset-password.js'),
    name: 'reset-password',
    path: '/reset-password',
  },
]);

const settingsRoutes: AppClientRouteContribution = defineSettingsRoutes([]);

const routes: readonly AppClientRouteContribution[] = [
  appRoutes,
  settingsRoutes,
];

export default routes;
