import { Blocks, Home, LayoutTemplate, ShoppingCart } from 'lucide-react';
import {
  defineAppRoutes,
  defineDevRoutes,
  defineSettingsRoutes,
  type AppClientRouteContribution,
} from '@nocobase/app-client/plugins';

const appRoutes: AppClientRouteContribution = defineAppRoutes([
  {
    // Every signed-in user reaches the landing page. `authz: 'skip'` takes it out of page authorization entirely, so
    // no permission change can leave a user signed in with nowhere to land.
    authz: 'skip',
    auth: 'required',
    componentLoader: () => import('./pages/home.js'),
    name: 'home',
    navigation: { title: 'navigation.home', icon: Home },
    path: '/',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/login.js'),
    name: 'login',
    path: '/login',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/register.js'),
    name: 'register',
    path: '/register',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/forgot-password.js'),
    name: 'forgot-password',
    path: '/forgot-password',
  },
  {
    auth: 'guest',
    componentLoader: () => import('./pages/auth/reset-password.js'),
    name: 'reset-password',
    path: '/reset-password',
  },
]);

const settingsRoutes: AppClientRouteContribution = defineSettingsRoutes([]);

// Reference pages for building application UI, mounted under `/dev` and dropped from a production build.
// `Examples` are complete business screens on mock data; `Components` shows one shadcn/ui primitive per page.
// Both groups share the frame in `client/pages/dev/shared.tsx`.
// The set is filled in page by page, and a dev route is declared together with the page it loads, never before it:
// the entries whose page is still to write stay commented out below. Uncomment one, and the lucide-react icon it
// names, when the page lands.
const devRoutes: AppClientRouteContribution = defineDevRoutes([
  {
    name: 'dev-examples',
    navigation: { title: 'devExamples.title', icon: LayoutTemplate },
    children: [
      // {
      //   name: 'dev-examples-dashboard',
      //   path: '/examples/dashboard',
      //   navigation: {
      //     title: 'devExamples.dashboard.title',
      //     icon: LayoutDashboard,
      //   },
      //   breadcrumb: { title: 'devExamples.dashboard.title' },
      //   componentLoader: () => import('./pages/dev/examples/dashboard.js'),
      // },
      {
        name: 'dev-examples-orders',
        path: '/examples/orders',
        navigation: { title: 'devExamples.orders.title', icon: ShoppingCart },
        breadcrumb: { title: 'devExamples.orders.title' },
        componentLoader: () => import('./pages/dev/examples/orders.js'),
      },
      // {
      //   name: 'dev-examples-customers',
      //   path: '/examples/customers',
      //   navigation: { title: 'devExamples.customers.title', icon: Users },
      //   breadcrumb: { title: 'devExamples.customers.title' },
      //   componentLoader: () => import('./pages/dev/examples/customers.js'),
      // },
      // {
      //   name: 'dev-examples-product-form',
      //   path: '/examples/product-form',
      //   navigation: {
      //     title: 'devExamples.productForm.title',
      //     icon: PackagePlus,
      //   },
      //   breadcrumb: { title: 'devExamples.productForm.title' },
      //   componentLoader: () => import('./pages/dev/examples/product-form.js'),
      // },
      // {
      //   name: 'dev-examples-inbox',
      //   path: '/examples/inbox',
      //   navigation: { title: 'devExamples.inbox.title', icon: MessagesSquare },
      //   breadcrumb: { title: 'devExamples.inbox.title' },
      //   componentLoader: () => import('./pages/dev/examples/inbox.js'),
      // },
      // {
      //   name: 'dev-examples-survey',
      //   path: '/examples/survey',
      //   navigation: { title: 'devExamples.survey.title', icon: ClipboardList },
      //   breadcrumb: { title: 'devExamples.survey.title' },
      //   componentLoader: () => import('./pages/dev/examples/survey.js'),
      // },
      // {
      //   name: 'dev-examples-team-settings',
      //   path: '/examples/team-settings',
      //   navigation: {
      //     title: 'devExamples.teamSettings.title',
      //     icon: Settings2,
      //   },
      //   breadcrumb: { title: 'devExamples.teamSettings.title' },
      //   componentLoader: () => import('./pages/dev/examples/team-settings.js'),
      // },
      // {
      //   name: 'dev-examples-schedule',
      //   path: '/examples/schedule',
      //   navigation: { title: 'devExamples.schedule.title', icon: CalendarDays },
      //   breadcrumb: { title: 'devExamples.schedule.title' },
      //   componentLoader: () => import('./pages/dev/examples/schedule.js'),
      // },
    ],
  },
  {
    name: 'dev-components',
    navigation: { title: 'devComponents.title', icon: Blocks },
    children: [
      {
        name: 'dev-components-accordion',
        path: '/components/accordion',
        navigation: { title: 'devComponents.accordion.title' },
        breadcrumb: { title: 'devComponents.accordion.title' },
        componentLoader: () => import('./pages/dev/components/accordion.js'),
      },
      {
        name: 'dev-components-alert',
        path: '/components/alert',
        navigation: { title: 'devComponents.alert.title' },
        breadcrumb: { title: 'devComponents.alert.title' },
        componentLoader: () => import('./pages/dev/components/alert.js'),
      },
      {
        name: 'dev-components-alert-dialog',
        path: '/components/alert-dialog',
        navigation: { title: 'devComponents.alertDialog.title' },
        breadcrumb: { title: 'devComponents.alertDialog.title' },
        componentLoader: () => import('./pages/dev/components/alert-dialog.js'),
      },
      {
        name: 'dev-components-aspect-ratio',
        path: '/components/aspect-ratio',
        navigation: { title: 'devComponents.aspectRatio.title' },
        breadcrumb: { title: 'devComponents.aspectRatio.title' },
        componentLoader: () => import('./pages/dev/components/aspect-ratio.js'),
      },
      {
        name: 'dev-components-attachment',
        path: '/components/attachment',
        navigation: { title: 'devComponents.attachment.title' },
        breadcrumb: { title: 'devComponents.attachment.title' },
        componentLoader: () => import('./pages/dev/components/attachment.js'),
      },
      {
        name: 'dev-components-avatar',
        path: '/components/avatar',
        navigation: { title: 'devComponents.avatar.title' },
        breadcrumb: { title: 'devComponents.avatar.title' },
        componentLoader: () => import('./pages/dev/components/avatar.js'),
      },
      {
        name: 'dev-components-badge',
        path: '/components/badge',
        navigation: { title: 'devComponents.badge.title' },
        breadcrumb: { title: 'devComponents.badge.title' },
        componentLoader: () => import('./pages/dev/components/badge.js'),
      },
      {
        name: 'dev-components-breadcrumb',
        path: '/components/breadcrumb',
        navigation: { title: 'devComponents.breadcrumb.title' },
        breadcrumb: { title: 'devComponents.breadcrumb.title' },
        componentLoader: () => import('./pages/dev/components/breadcrumb.js'),
      },
      {
        name: 'dev-components-bubble',
        path: '/components/bubble',
        navigation: { title: 'devComponents.bubble.title' },
        breadcrumb: { title: 'devComponents.bubble.title' },
        componentLoader: () => import('./pages/dev/components/bubble.js'),
      },
      {
        name: 'dev-components-button',
        path: '/components/button',
        navigation: { title: 'devComponents.button.title' },
        breadcrumb: { title: 'devComponents.button.title' },
        componentLoader: () => import('./pages/dev/components/button.js'),
      },
      {
        name: 'dev-components-button-group',
        path: '/components/button-group',
        navigation: { title: 'devComponents.buttonGroup.title' },
        breadcrumb: { title: 'devComponents.buttonGroup.title' },
        componentLoader: () => import('./pages/dev/components/button-group.js'),
      },
      {
        name: 'dev-components-calendar',
        path: '/components/calendar',
        navigation: { title: 'devComponents.calendar.title' },
        breadcrumb: { title: 'devComponents.calendar.title' },
        componentLoader: () => import('./pages/dev/components/calendar.js'),
      },
      {
        name: 'dev-components-card',
        path: '/components/card',
        navigation: { title: 'devComponents.card.title' },
        breadcrumb: { title: 'devComponents.card.title' },
        componentLoader: () => import('./pages/dev/components/card.js'),
      },
      {
        name: 'dev-components-carousel',
        path: '/components/carousel',
        navigation: { title: 'devComponents.carousel.title' },
        breadcrumb: { title: 'devComponents.carousel.title' },
        componentLoader: () => import('./pages/dev/components/carousel.js'),
      },
      {
        name: 'dev-components-chart',
        path: '/components/chart',
        navigation: { title: 'devComponents.chart.title' },
        breadcrumb: { title: 'devComponents.chart.title' },
        componentLoader: () => import('./pages/dev/components/chart.js'),
      },
      {
        name: 'dev-components-checkbox',
        path: '/components/checkbox',
        navigation: { title: 'devComponents.checkbox.title' },
        breadcrumb: { title: 'devComponents.checkbox.title' },
        componentLoader: () => import('./pages/dev/components/checkbox.js'),
      },
      {
        name: 'dev-components-collapsible',
        path: '/components/collapsible',
        navigation: { title: 'devComponents.collapsible.title' },
        breadcrumb: { title: 'devComponents.collapsible.title' },
        componentLoader: () => import('./pages/dev/components/collapsible.js'),
      },
      {
        name: 'dev-components-combobox',
        path: '/components/combobox',
        navigation: { title: 'devComponents.combobox.title' },
        breadcrumb: { title: 'devComponents.combobox.title' },
        componentLoader: () => import('./pages/dev/components/combobox.js'),
      },
      {
        name: 'dev-components-command',
        path: '/components/command',
        navigation: { title: 'devComponents.command.title' },
        breadcrumb: { title: 'devComponents.command.title' },
        componentLoader: () => import('./pages/dev/components/command.js'),
      },
      {
        name: 'dev-components-context-menu',
        path: '/components/context-menu',
        navigation: { title: 'devComponents.contextMenu.title' },
        breadcrumb: { title: 'devComponents.contextMenu.title' },
        componentLoader: () => import('./pages/dev/components/context-menu.js'),
      },
      {
        name: 'dev-components-data-table',
        path: '/components/data-table',
        navigation: { title: 'devComponents.dataTable.title' },
        breadcrumb: { title: 'devComponents.dataTable.title' },
        componentLoader: () => import('./pages/dev/components/data-table.js'),
      },
      {
        name: 'dev-components-date-picker',
        path: '/components/date-picker',
        navigation: { title: 'devComponents.datePicker.title' },
        breadcrumb: { title: 'devComponents.datePicker.title' },
        componentLoader: () => import('./pages/dev/components/date-picker.js'),
      },
      {
        name: 'dev-components-dialog',
        path: '/components/dialog',
        navigation: { title: 'devComponents.dialog.title' },
        breadcrumb: { title: 'devComponents.dialog.title' },
        componentLoader: () => import('./pages/dev/components/dialog.js'),
      },
      // {
      //   name: 'dev-components-direction',
      //   path: '/components/direction',
      //   navigation: { title: 'devComponents.direction.title' },
      //   breadcrumb: { title: 'devComponents.direction.title' },
      //   componentLoader: () => import('./pages/dev/components/direction.js'),
      // },
      // {
      //   name: 'dev-components-drawer',
      //   path: '/components/drawer',
      //   navigation: { title: 'devComponents.drawer.title' },
      //   breadcrumb: { title: 'devComponents.drawer.title' },
      //   componentLoader: () => import('./pages/dev/components/drawer.js'),
      // },
      // {
      //   name: 'dev-components-dropdown-menu',
      //   path: '/components/dropdown-menu',
      //   navigation: { title: 'devComponents.dropdownMenu.title' },
      //   breadcrumb: { title: 'devComponents.dropdownMenu.title' },
      //   componentLoader: () =>
      //     import('./pages/dev/components/dropdown-menu.js'),
      // },
      // {
      //   name: 'dev-components-empty',
      //   path: '/components/empty',
      //   navigation: { title: 'devComponents.empty.title' },
      //   breadcrumb: { title: 'devComponents.empty.title' },
      //   componentLoader: () => import('./pages/dev/components/empty.js'),
      // },
      // {
      //   name: 'dev-components-field',
      //   path: '/components/field',
      //   navigation: { title: 'devComponents.field.title' },
      //   breadcrumb: { title: 'devComponents.field.title' },
      //   componentLoader: () => import('./pages/dev/components/field.js'),
      // },
      // {
      //   name: 'dev-components-hover-card',
      //   path: '/components/hover-card',
      //   navigation: { title: 'devComponents.hoverCard.title' },
      //   breadcrumb: { title: 'devComponents.hoverCard.title' },
      //   componentLoader: () => import('./pages/dev/components/hover-card.js'),
      // },
      // {
      //   name: 'dev-components-input',
      //   path: '/components/input',
      //   navigation: { title: 'devComponents.input.title' },
      //   breadcrumb: { title: 'devComponents.input.title' },
      //   componentLoader: () => import('./pages/dev/components/input.js'),
      // },
      // {
      //   name: 'dev-components-input-group',
      //   path: '/components/input-group',
      //   navigation: { title: 'devComponents.inputGroup.title' },
      //   breadcrumb: { title: 'devComponents.inputGroup.title' },
      //   componentLoader: () => import('./pages/dev/components/input-group.js'),
      // },
      // {
      //   name: 'dev-components-input-otp',
      //   path: '/components/input-otp',
      //   navigation: { title: 'devComponents.inputOtp.title' },
      //   breadcrumb: { title: 'devComponents.inputOtp.title' },
      //   componentLoader: () => import('./pages/dev/components/input-otp.js'),
      // },
      // {
      //   name: 'dev-components-item',
      //   path: '/components/item',
      //   navigation: { title: 'devComponents.item.title' },
      //   breadcrumb: { title: 'devComponents.item.title' },
      //   componentLoader: () => import('./pages/dev/components/item.js'),
      // },
      // {
      //   name: 'dev-components-kbd',
      //   path: '/components/kbd',
      //   navigation: { title: 'devComponents.kbd.title' },
      //   breadcrumb: { title: 'devComponents.kbd.title' },
      //   componentLoader: () => import('./pages/dev/components/kbd.js'),
      // },
      // {
      //   name: 'dev-components-label',
      //   path: '/components/label',
      //   navigation: { title: 'devComponents.label.title' },
      //   breadcrumb: { title: 'devComponents.label.title' },
      //   componentLoader: () => import('./pages/dev/components/label.js'),
      // },
      // {
      //   name: 'dev-components-marker',
      //   path: '/components/marker',
      //   navigation: { title: 'devComponents.marker.title' },
      //   breadcrumb: { title: 'devComponents.marker.title' },
      //   componentLoader: () => import('./pages/dev/components/marker.js'),
      // },
      // {
      //   name: 'dev-components-menubar',
      //   path: '/components/menubar',
      //   navigation: { title: 'devComponents.menubar.title' },
      //   breadcrumb: { title: 'devComponents.menubar.title' },
      //   componentLoader: () => import('./pages/dev/components/menubar.js'),
      // },
      // {
      //   name: 'dev-components-message',
      //   path: '/components/message',
      //   navigation: { title: 'devComponents.message.title' },
      //   breadcrumb: { title: 'devComponents.message.title' },
      //   componentLoader: () => import('./pages/dev/components/message.js'),
      // },
      // {
      //   name: 'dev-components-message-scroller',
      //   path: '/components/message-scroller',
      //   navigation: { title: 'devComponents.messageScroller.title' },
      //   breadcrumb: { title: 'devComponents.messageScroller.title' },
      //   componentLoader: () =>
      //     import('./pages/dev/components/message-scroller.js'),
      // },
      // {
      //   name: 'dev-components-native-select',
      //   path: '/components/native-select',
      //   navigation: { title: 'devComponents.nativeSelect.title' },
      //   breadcrumb: { title: 'devComponents.nativeSelect.title' },
      //   componentLoader: () =>
      //     import('./pages/dev/components/native-select.js'),
      // },
      // {
      //   name: 'dev-components-navigation-menu',
      //   path: '/components/navigation-menu',
      //   navigation: { title: 'devComponents.navigationMenu.title' },
      //   breadcrumb: { title: 'devComponents.navigationMenu.title' },
      //   componentLoader: () =>
      //     import('./pages/dev/components/navigation-menu.js'),
      // },
      // {
      //   name: 'dev-components-pagination',
      //   path: '/components/pagination',
      //   navigation: { title: 'devComponents.pagination.title' },
      //   breadcrumb: { title: 'devComponents.pagination.title' },
      //   componentLoader: () => import('./pages/dev/components/pagination.js'),
      // },
      // {
      //   name: 'dev-components-popover',
      //   path: '/components/popover',
      //   navigation: { title: 'devComponents.popover.title' },
      //   breadcrumb: { title: 'devComponents.popover.title' },
      //   componentLoader: () => import('./pages/dev/components/popover.js'),
      // },
      // {
      //   name: 'dev-components-progress',
      //   path: '/components/progress',
      //   navigation: { title: 'devComponents.progress.title' },
      //   breadcrumb: { title: 'devComponents.progress.title' },
      //   componentLoader: () => import('./pages/dev/components/progress.js'),
      // },
      // {
      //   name: 'dev-components-questionnaire',
      //   path: '/components/questionnaire',
      //   navigation: { title: 'devComponents.questionnaire.title' },
      //   breadcrumb: { title: 'devComponents.questionnaire.title' },
      //   componentLoader: () =>
      //     import('./pages/dev/components/questionnaire.js'),
      // },
      // {
      //   name: 'dev-components-radio-group',
      //   path: '/components/radio-group',
      //   navigation: { title: 'devComponents.radioGroup.title' },
      //   breadcrumb: { title: 'devComponents.radioGroup.title' },
      //   componentLoader: () => import('./pages/dev/components/radio-group.js'),
      // },
      // {
      //   name: 'dev-components-resizable',
      //   path: '/components/resizable',
      //   navigation: { title: 'devComponents.resizable.title' },
      //   breadcrumb: { title: 'devComponents.resizable.title' },
      //   componentLoader: () => import('./pages/dev/components/resizable.js'),
      // },
      // {
      //   name: 'dev-components-scroll-area',
      //   path: '/components/scroll-area',
      //   navigation: { title: 'devComponents.scrollArea.title' },
      //   breadcrumb: { title: 'devComponents.scrollArea.title' },
      //   componentLoader: () => import('./pages/dev/components/scroll-area.js'),
      // },
      // {
      //   name: 'dev-components-select',
      //   path: '/components/select',
      //   navigation: { title: 'devComponents.select.title' },
      //   breadcrumb: { title: 'devComponents.select.title' },
      //   componentLoader: () => import('./pages/dev/components/select.js'),
      // },
      {
        name: 'dev-components-separator',
        path: '/components/separator',
        navigation: { title: 'devComponents.separator.title' },
        breadcrumb: { title: 'devComponents.separator.title' },
        componentLoader: () => import('./pages/dev/components/separator.js'),
      },
      {
        name: 'dev-components-sheet',
        path: '/components/sheet',
        navigation: { title: 'devComponents.sheet.title' },
        breadcrumb: { title: 'devComponents.sheet.title' },
        componentLoader: () => import('./pages/dev/components/sheet.js'),
      },
      {
        name: 'dev-components-sidebar',
        path: '/components/sidebar',
        navigation: { title: 'devComponents.sidebar.title' },
        breadcrumb: { title: 'devComponents.sidebar.title' },
        componentLoader: () => import('./pages/dev/components/sidebar.js'),
      },
      {
        name: 'dev-components-skeleton',
        path: '/components/skeleton',
        navigation: { title: 'devComponents.skeleton.title' },
        breadcrumb: { title: 'devComponents.skeleton.title' },
        componentLoader: () => import('./pages/dev/components/skeleton.js'),
      },
      {
        name: 'dev-components-slider',
        path: '/components/slider',
        navigation: { title: 'devComponents.slider.title' },
        breadcrumb: { title: 'devComponents.slider.title' },
        componentLoader: () => import('./pages/dev/components/slider.js'),
      },
      {
        name: 'dev-components-spinner',
        path: '/components/spinner',
        navigation: { title: 'devComponents.spinner.title' },
        breadcrumb: { title: 'devComponents.spinner.title' },
        componentLoader: () => import('./pages/dev/components/spinner.js'),
      },
      {
        name: 'dev-components-switch',
        path: '/components/switch',
        navigation: { title: 'devComponents.switch.title' },
        breadcrumb: { title: 'devComponents.switch.title' },
        componentLoader: () => import('./pages/dev/components/switch.js'),
      },
      {
        name: 'dev-components-table',
        path: '/components/table',
        navigation: { title: 'devComponents.table.title' },
        breadcrumb: { title: 'devComponents.table.title' },
        componentLoader: () => import('./pages/dev/components/table.js'),
      },
      // {
      //   name: 'dev-components-tabs',
      //   path: '/components/tabs',
      //   navigation: { title: 'devComponents.tabs.title' },
      //   breadcrumb: { title: 'devComponents.tabs.title' },
      //   componentLoader: () => import('./pages/dev/components/tabs.js'),
      // },
      // {
      //   name: 'dev-components-textarea',
      //   path: '/components/textarea',
      //   navigation: { title: 'devComponents.textarea.title' },
      //   breadcrumb: { title: 'devComponents.textarea.title' },
      //   componentLoader: () => import('./pages/dev/components/textarea.js'),
      // },
      // {
      //   name: 'dev-components-toast',
      //   path: '/components/toast',
      //   navigation: { title: 'devComponents.toast.title' },
      //   breadcrumb: { title: 'devComponents.toast.title' },
      //   componentLoader: () => import('./pages/dev/components/toast.js'),
      // },
      // {
      //   name: 'dev-components-toggle',
      //   path: '/components/toggle',
      //   navigation: { title: 'devComponents.toggle.title' },
      //   breadcrumb: { title: 'devComponents.toggle.title' },
      //   componentLoader: () => import('./pages/dev/components/toggle.js'),
      // },
      // {
      //   name: 'dev-components-toggle-group',
      //   path: '/components/toggle-group',
      //   navigation: { title: 'devComponents.toggleGroup.title' },
      //   breadcrumb: { title: 'devComponents.toggleGroup.title' },
      //   componentLoader: () => import('./pages/dev/components/toggle-group.js'),
      // },
      // {
      //   name: 'dev-components-tooltip',
      //   path: '/components/tooltip',
      //   navigation: { title: 'devComponents.tooltip.title' },
      //   breadcrumb: { title: 'devComponents.tooltip.title' },
      //   componentLoader: () => import('./pages/dev/components/tooltip.js'),
      // },
      // {
      //   name: 'dev-components-typography',
      //   path: '/components/typography',
      //   navigation: { title: 'devComponents.typography.title' },
      //   breadcrumb: { title: 'devComponents.typography.title' },
      //   componentLoader: () => import('./pages/dev/components/typography.js'),
      // },
    ],
  },
]);

const routes: readonly AppClientRouteContribution[] = [
  appRoutes,
  settingsRoutes,
  devRoutes,
];

export default routes;
