import { z } from 'zod';
import type {
  Overview,
  Preview,
  RecordDetail,
  Created,
  LabSettings,
} from '../../shared/types.js';

// Response schemas follow the shared service views; scenario-owned JSON remains JSON.
export const OverviewSchema: z.ZodType<Overview> = z
  .object({
    people: z.array(
      z.object({
        id: z.string(),
        active: z.boolean(),
        manager: z.union([z.null(), z.string()]),
        roles: z.array(z.string()),
      }),
    ),
    records: z.array(
      z.object({
        lifecycle: z.string(),
        id: z.string(),
        demo: z.union([
          z.null(),
          z.literal('leave'),
          z.literal('ruledLeave'),
          z.literal('compensatory'),
          z.literal('trip'),
          z.literal('purchaseChain'),
          z.literal('purchase'),
          z.literal('committee'),
          z.literal('contract'),
          z.literal('contractReview'),
          z.literal('contractFullReview'),
          z.literal('countersign'),
          z.literal('legalReview'),
          z.literal('counsel'),
          z.literal('matter'),
          z.literal('reimbursement'),
          z.literal('expense'),
          z.literal('payment'),
          z.literal('financeFirst'),
          z.literal('financeAny'),
          z.literal('pool'),
          z.literal('paymentApproval'),
          z.literal('grantRequest'),
          z.literal('supplier'),
          z.literal('onboarding'),
          z.literal('launch'),
          z.literal('notice'),
          z.literal('order'),
        ]),
        business: z.union([
          z.null(),
          z.literal('leave'),
          z.literal('purchase'),
          z.literal('contract'),
          z.literal('reimbursement'),
          z.literal('payment'),
          z.literal('supplier'),
          z.literal('onboarding'),
          z.literal('launch'),
          z.literal('notice'),
          z.literal('order'),
          z.literal('travel'),
          z.literal('grant'),
        ]),
        title: z.union([z.null(), z.string()]),
        status: z.string(),
        applicantId: z.union([z.null(), z.string()]),
        parent: z.union([
          z.null(),
          z.object({ lifecycle: z.string(), id: z.string() }),
        ]),
        createdAt: z.union([z.null(), z.string()]),
        changedAt: z.union([z.null(), z.string()]),
        handlers: z.array(z.string()),
        stage: z.union([z.null(), z.string()]),
        facts: z.record(z.string(), z.json()),
      }),
    ),
    inbox: z.array(
      z.object({
        box: z.union([
          z.literal('toDo'),
          z.literal('done'),
          z.literal('mine'),
          z.literal('copiedToMe'),
        ]),
        lifecycle: z.string(),
        recordId: z.string(),
        source: z.union([
          z.literal('task'),
          z.literal('acknowledgement'),
          z.literal('transition'),
          z.literal('record'),
        ]),
        taskId: z.union([z.null(), z.string()]),
        action: z.union([z.null(), z.string()]),
        detail: z.union([z.null(), z.string()]),
        since: z.union([z.null(), z.string()]),
        onBehalfOf: z.union([z.null(), z.string()]),
      }),
    ),
    messages: z.array(
      z.object({
        id: z.string(),
        recipientId: z.string(),
        subject: z.string(),
        createdAt: z.string(),
      }),
    ),
    operations: z.array(
      z.object({
        id: z.string(),
        kind: z.string(),
        key: z.string(),
        input: z.record(z.string(), z.json()),
        result: z.record(z.string(), z.json()),
        createdAt: z.string(),
      }),
    ),
    settings: z.object({
      managers: z.record(z.string(), z.string()).optional(),
      roles: z.record(z.string(), z.array(z.string())).optional(),
      inactive: z.array(z.string()).optional(),
      delegations: z
        .array(
          z.object({
            from: z.string(),
            to: z.string(),
            start: z.string(),
            end: z.string(),
            kinds: z.array(z.string()),
            coversExisting: z.boolean(),
          }),
        )
        .optional(),
      ruleVersion: z.number().optional(),
      failOperation: z.string().optional(),
      declinePayment: z.union([z.literal(false), z.literal(true)]).optional(),
      highRisk: z.union([z.literal(false), z.literal(true)]).optional(),
    }),
  })
  .meta({ ref: 'ApprovalExampleOverview' });
export const PreviewSchema: z.ZodType<Preview> = z
  .object({
    mode: z.union([
      z.literal('stages'),
      z.literal('branches'),
      z.literal('none'),
    ]),
    steps: z.array(
      z.object({
        key: z.string(),
        title: z.union([z.null(), z.string()]),
        kind: z.union([z.literal('stage'), z.literal('branch')]),
        rule: z.string(),
        people: z.array(z.string()),
        included: z.boolean(),
        required: z.boolean(),
        because: z.union([z.null(), z.string()]),
      }),
    ),
    problems: z.array(z.string()),
    notes: z.array(z.string()),
  })
  .meta({ ref: 'ApprovalExamplePreview' });
export const RecordDetailSchema: z.ZodType<RecordDetail> = z
  .object({
    summary: z.object({
      lifecycle: z.string(),
      id: z.string(),
      demo: z.union([
        z.null(),
        z.literal('leave'),
        z.literal('ruledLeave'),
        z.literal('compensatory'),
        z.literal('trip'),
        z.literal('purchaseChain'),
        z.literal('purchase'),
        z.literal('committee'),
        z.literal('contract'),
        z.literal('contractReview'),
        z.literal('contractFullReview'),
        z.literal('countersign'),
        z.literal('legalReview'),
        z.literal('counsel'),
        z.literal('matter'),
        z.literal('reimbursement'),
        z.literal('expense'),
        z.literal('payment'),
        z.literal('financeFirst'),
        z.literal('financeAny'),
        z.literal('pool'),
        z.literal('paymentApproval'),
        z.literal('grantRequest'),
        z.literal('supplier'),
        z.literal('onboarding'),
        z.literal('launch'),
        z.literal('notice'),
        z.literal('order'),
      ]),
      business: z.union([
        z.null(),
        z.literal('leave'),
        z.literal('purchase'),
        z.literal('contract'),
        z.literal('reimbursement'),
        z.literal('payment'),
        z.literal('supplier'),
        z.literal('onboarding'),
        z.literal('launch'),
        z.literal('notice'),
        z.literal('order'),
        z.literal('travel'),
        z.literal('grant'),
      ]),
      title: z.union([z.null(), z.string()]),
      status: z.string(),
      applicantId: z.union([z.null(), z.string()]),
      parent: z.union([
        z.null(),
        z.object({ lifecycle: z.string(), id: z.string() }),
      ]),
      createdAt: z.union([z.null(), z.string()]),
      changedAt: z.union([z.null(), z.string()]),
      handlers: z.array(z.string()),
      stage: z.union([z.null(), z.string()]),
      facts: z.record(z.string(), z.json()),
    }),
    record: z.object({ id: z.string() }),
    state: z.string(),
    version: z.union([z.null(), z.number()]),
    available: z.array(
      z.object({
        name: z.string(),
        title: z.string(),
        to: z.array(z.string()),
        allowed: z.boolean(),
        blockers: z.array(
          z.object({
            source: z.union([
              z.literal('state'),
              z.literal('guard'),
              z.literal('manual'),
            ]),
            kind: z.union([z.literal('permission'), z.literal('precondition')]),
            code: z.string(),
            message: z.string(),
          }),
        ),
      }),
    ),
    history: z.array(
      z.object({
        id: z.string(),
        lifecycle: z.string(),
        recordId: z.string(),
        transition: z.string(),
        from: z.union([z.null(), z.string()]),
        to: z.string(),
        actorId: z.string(),
        input: z.record(z.string(), z.json()),
        at: z.string(),
        version: z.number(),
        requestId: z.union([z.null(), z.string()]),
      }),
    ),
    runs: z.array(
      z.object({
        run: z.object({
          id: z.string(),
          source: z.string(),
          lifecycle: z.string(),
          recordId: z.string(),
          applicantId: z.string(),
          version: z.number(),
          status: z.string(),
          lifecycleVersion: z.number(),
          plan: z.array(
            z.object({
              stage: z.string(),
              included: z.boolean(),
              because: z.union([z.null(), z.string()]),
              people: z.union([z.null(), z.array(z.string())]),
            }),
          ),
          settings: z.record(z.string(), z.json()),
          parameters: z.record(z.string(), z.json()),
          outcome: z.union([z.null(), z.string()]),
          submitted: z.record(z.string(), z.json()),
          changes: z.array(
            z.object({
              stage: z.string(),
              taskId: z.string(),
              actorId: z.string(),
              values: z.record(z.string(), z.json()),
              reason: z.union([z.null(), z.string()]),
              at: z.string(),
            }),
          ),
          content: z.record(z.string(), z.json()),
          contentHash: z.string(),
          previousRunId: z.union([z.null(), z.string()]),
          resumeAt: z.union([z.null(), z.string()]),
          returnedBy: z.union([
            z.null(),
            z.object({ stage: z.string(), resume: z.boolean() }),
          ]),
          startedAt: z.string(),
          startedBy: z.string(),
          endedAt: z.union([z.null(), z.string()]),
          endedBy: z.union([z.null(), z.string()]),
          endedWith: z.union([z.null(), z.string()]),
          note: z.union([z.null(), z.string()]),
          sequence: z.number(),
          rowVersion: z.number(),
        }),
        stages: z.array(
          z.object({
            key: z.string(),
            title: z.union([z.null(), z.string()]),
            policy: z.string(),
            included: z.boolean(),
            because: z.union([z.null(), z.string()]),
            state: z.union([
              z.literal('done'),
              z.literal('current'),
              z.literal('waiting'),
              z.literal('skipped'),
            ]),
            canRevise: z.array(z.string()),
            answers: z.array(z.string()),
          }),
        ),
        tasks: z.array(
          z.object({
            id: z.string(),
            source: z.string(),
            lifecycle: z.string(),
            recordId: z.string(),
            runId: z.string(),
            stage: z.string(),
            enteredVersion: z.number(),
            kind: z.union([
              z.literal('decide'),
              z.literal('consult'),
              z.literal('material'),
              z.literal('copy'),
            ]),
            role: z.union([z.literal('member'), z.literal('gate')]),
            mode: z.union([
              z.null(),
              z.literal('before'),
              z.literal('after'),
              z.literal('alongside'),
            ]),
            gates: z.union([z.null(), z.string()]),
            depth: z.number(),
            order: z.number(),
            subject: z.union([z.null(), z.string()]),
            assigneeId: z.string(),
            via: z.union([
              z.literal('consult'),
              z.literal('material'),
              z.literal('copy'),
              z.literal('plan'),
              z.literal('transfer'),
              z.literal('reassign'),
              z.literal('escalate'),
              z.literal('addSigner'),
              z.literal('assign'),
            ]),
            note: z.union([z.null(), z.string()]),
            previousTaskId: z.union([z.null(), z.string()]),
            status: z.union([
              z.literal('waiting'),
              z.literal('pending'),
              z.literal('blocked'),
              z.literal('candidate'),
              z.literal('claimed'),
              z.literal('suspended'),
              z.literal('completed'),
              z.literal('voided'),
              z.literal('transferred'),
            ]),
            answer: z.union([z.null(), z.string()]),
            comment: z.union([z.null(), z.string()]),
            data: z.union([z.null(), z.record(z.string(), z.json())]),
            actorId: z.union([z.null(), z.string()]),
            contentHash: z.union([z.null(), z.string()]),
            requestId: z.union([z.null(), z.string()]),
            createdAt: z.string(),
            claimedAt: z.union([z.null(), z.string()]),
            remindAt: z.union([z.null(), z.string()]),
            dueAt: z.union([z.null(), z.string()]),
            closedAt: z.union([z.null(), z.string()]),
            closeReason: z.union([z.null(), z.string()]),
            seq: z.union([z.null(), z.number()]),
            rowVersion: z.number(),
          }),
        ),
        events: z.array(
          z.object({
            id: z.string(),
            runId: z.string(),
            source: z.string(),
            lifecycle: z.string(),
            recordId: z.string(),
            stage: z.union([z.null(), z.string()]),
            taskId: z.union([z.null(), z.string()]),
            kind: z.string(),
            actorId: z.string(),
            message: z.union([z.null(), z.string()]),
            data: z.record(z.string(), z.json()),
            at: z.string(),
          }),
        ),
        history: z.array(
          z.object({
            id: z.string(),
            lifecycle: z.string(),
            recordId: z.string(),
            transition: z.string(),
            from: z.union([z.null(), z.string()]),
            to: z.string(),
            actorId: z.string(),
            input: z.record(z.string(), z.json()),
            at: z.string(),
            version: z.number(),
            requestId: z.union([z.null(), z.string()]),
          }),
        ),
        returnTargets: z.array(z.string()),
      }),
    ),
    actions: z.array(
      z.object({
        task: z.object({
          id: z.string(),
          source: z.string(),
          lifecycle: z.string(),
          recordId: z.string(),
          runId: z.string(),
          stage: z.string(),
          enteredVersion: z.number(),
          kind: z.union([
            z.literal('decide'),
            z.literal('consult'),
            z.literal('material'),
            z.literal('copy'),
          ]),
          role: z.union([z.literal('member'), z.literal('gate')]),
          mode: z.union([
            z.null(),
            z.literal('before'),
            z.literal('after'),
            z.literal('alongside'),
          ]),
          gates: z.union([z.null(), z.string()]),
          depth: z.number(),
          order: z.number(),
          subject: z.union([z.null(), z.string()]),
          assigneeId: z.string(),
          via: z.union([
            z.literal('consult'),
            z.literal('material'),
            z.literal('copy'),
            z.literal('plan'),
            z.literal('transfer'),
            z.literal('reassign'),
            z.literal('escalate'),
            z.literal('addSigner'),
            z.literal('assign'),
          ]),
          note: z.union([z.null(), z.string()]),
          previousTaskId: z.union([z.null(), z.string()]),
          status: z.union([
            z.literal('waiting'),
            z.literal('pending'),
            z.literal('blocked'),
            z.literal('candidate'),
            z.literal('claimed'),
            z.literal('suspended'),
            z.literal('completed'),
            z.literal('voided'),
            z.literal('transferred'),
          ]),
          answer: z.union([z.null(), z.string()]),
          comment: z.union([z.null(), z.string()]),
          data: z.union([z.null(), z.record(z.string(), z.json())]),
          actorId: z.union([z.null(), z.string()]),
          contentHash: z.union([z.null(), z.string()]),
          requestId: z.union([z.null(), z.string()]),
          createdAt: z.string(),
          claimedAt: z.union([z.null(), z.string()]),
          remindAt: z.union([z.null(), z.string()]),
          dueAt: z.union([z.null(), z.string()]),
          closedAt: z.union([z.null(), z.string()]),
          closeReason: z.union([z.null(), z.string()]),
          seq: z.union([z.null(), z.number()]),
          rowVersion: z.number(),
        }),
        onBehalfOf: z.union([z.null(), z.string()]),
        actions: z.array(z.string()),
      }),
    ),
    admin: z.array(
      z.object({
        action: z.union([
          z.literal('reassign'),
          z.literal('assign'),
          z.literal('appoint'),
          z.literal('migrate'),
        ]),
        taskId: z.union([z.null(), z.string()]),
        approval: z.string(),
        assigneeId: z.union([z.null(), z.string()]),
        candidates: z.array(z.string()),
      }),
    ),
    branches: z.array(
      z.object({
        key: z.string(),
        title: z.string(),
        kind: z.string(),
        required: z.boolean(),
        status: z.union([z.literal('active'), z.literal('superseded')]),
        revision: z.number(),
        because: z.union([z.null(), z.string()]),
        childLifecycle: z.string(),
        childId: z.string(),
        childStatus: z.string(),
      }),
    ),
    acknowledgements: z.array(
      z.object({
        id: z.string(),
        recipientId: z.string(),
        kind: z.string(),
        status: z.string(),
        readAt: z.union([z.null(), z.string()]),
        confirmedAt: z.union([z.null(), z.string()]),
        comments: z.array(
          z.object({ authorId: z.string(), text: z.string(), at: z.string() }),
        ),
      }),
    ),
    extras: z.record(z.string(), z.json()),
    effects: z.array(
      z.object({
        id: z.string(),
        transitionId: z.string(),
        lifecycle: z.string(),
        recordId: z.string(),
        effect: z.string(),
        status: z.union([
          z.literal('queued'),
          z.literal('running'),
          z.literal('succeeded'),
          z.literal('failed'),
          z.literal('dead'),
          z.literal('cancelled'),
        ]),
        attempts: z.number(),
        maxAttempts: z.number(),
        result: z.json(),
        error: z.union([z.null(), z.string()]),
        createdAt: z.string(),
        updatedAt: z.string(),
        claimedAt: z.union([z.null(), z.string()]),
        runAfter: z.union([z.null(), z.string()]),
      }),
    ),
    description: z.object({
      name: z.string(),
      initial: z.string(),
      initialStates: z.array(z.string()),
      states: z.array(z.string()),
      stateInfo: z.array(
        z.object({
          name: z.string(),
          title: z.string(),
          final: z.boolean(),
          meta: z.record(z.string(), z.json()),
        }),
      ),
      transitions: z.array(
        z.object({
          name: z.string(),
          title: z.string(),
          from: z.array(z.string()),
          to: z.array(z.string()),
          effects: z.array(z.string()),
          accept: z.array(z.string()),
          manual: z.boolean(),
          meta: z.record(z.string(), z.json()),
        }),
      ),
      continuations: z.array(
        z.object({
          effect: z.string(),
          onSuccess: z.string().optional(),
          onFailure: z.string().optional(),
        }),
      ),
      onEnter: z.record(z.string(), z.array(z.string())),
      triggers: z.array(
        z.object({
          name: z.string(),
          transition: z.string(),
          when: z.array(z.string()),
        }),
      ),
    }),
    diagram: z.string(),
  })
  .meta({ ref: 'ApprovalExampleRecordDetail' });
export const CreatedSchema: z.ZodType<Created> = z
  .object({ lifecycle: z.string(), id: z.string(), status: z.string() })
  .meta({ ref: 'ApprovalExampleCreated' });
export const LabSettingsSchema: z.ZodType<LabSettings> = z
  .object({
    managers: z.record(z.string(), z.string()).optional(),
    roles: z.record(z.string(), z.array(z.string())).optional(),
    inactive: z.array(z.string()).optional(),
    delegations: z
      .array(
        z.object({
          from: z.string(),
          to: z.string(),
          start: z.string(),
          end: z.string(),
          kinds: z.array(z.string()),
          coversExisting: z.boolean(),
        }),
      )
      .optional(),
    ruleVersion: z.number().optional(),
    failOperation: z.string().optional(),
    declinePayment: z.union([z.literal(false), z.literal(true)]).optional(),
    highRisk: z.union([z.literal(false), z.literal(true)]).optional(),
  })
  .meta({ ref: 'ApprovalExampleLabSettings' });

// Scenario forms and transition inputs are user-defined JSON objects; their business validation remains in the services.
const jsonObject = z.record(z.string(), z.json());
export const EmptyInput: z.ZodType<Record<string, never>> = z.strictObject({});
export const SettingsInput: z.ZodType<LabSettings> = z.strictObject({
  managers: z.record(z.string(), z.string()).optional(),
  roles: z.record(z.string(), z.array(z.string())).optional(),
  inactive: z.array(z.string()).optional(),
  delegations: z
    .array(
      z.strictObject({
        from: z.string(),
        to: z.string(),
        start: z.iso.datetime(),
        end: z.iso.datetime(),
        kinds: z.array(z.string()),
        coversExisting: z.boolean(),
      }),
    )
    .optional(),
  ruleVersion: z.number().int().positive().optional(),
  failOperation: z.string().optional(),
  declinePayment: z.boolean().optional(),
  highRisk: z.boolean().optional(),
});
export const TaskInputs: Readonly<
  Record<string, z.ZodType<import('@nocobase/lifecycle').JsonObject>>
> = {
  respond: z.strictObject({
    answer: z.string(),
    comment: z.string().optional(),
    data: jsonObject.optional(),
    contentHash: z.string().optional(),
    requestId: z.string().min(1).regex(/^[^$]/).optional(),
  }),
  claim: z.strictObject({}),
  release: z.strictObject({}),
  transfer: z.strictObject({ to: z.string(), reason: z.string() }),
  reassign: z.strictObject({
    to: z.string(),
    reason: z.string(),
    override: z.boolean().optional(),
  }),
  assign: z.strictObject({ to: z.string() }),
  addSigner: z.strictObject({
    person: z.string(),
    mode: z.enum(['before', 'after', 'alongside']),
  }),
  consult: z.strictObject({ person: z.string(), question: z.string() }),
  askMaterial: z.strictObject({ request: z.string() }),
  returnTo: z.strictObject({
    to: z.string(),
    reason: z.string(),
    resume: z.boolean().optional(),
  }),
  revise: z.strictObject({ values: jsonObject, reason: z.string() }),
};
export const RecordInputs: Readonly<
  Record<string, z.ZodType<import('@nocobase/lifecycle').JsonObject>>
> = {
  read: z.strictObject({}),
  confirm: z.strictObject({ comment: z.string().optional() }),
  comment: z.strictObject({ comment: z.string() }),
  useGrant: z.strictObject({
    amountCents: z.number().int().positive(),
    usageKey: z.string().optional(),
  }),
  askAgain: z.strictObject({}),
  appoint: z.strictObject({
    approval: z.string(),
    to: z.string(),
    reason: z.string(),
  }),
  migrate: z.strictObject({
    approval: z.string(),
    version: z.number().int().positive(),
    reason: z.string(),
  }),
};
export const EventInput: z.ZodType<import('@nocobase/lifecycle').JsonObject> =
  z.strictObject({
    eventId: z.string().optional(),
    paymentRef: z.string().optional(),
    depositRef: z.string().optional(),
  });

import type { RecordSummary } from '../../shared/types.js';
export const RecordSummarySchema: z.ZodType<RecordSummary> = z
  .object({
    lifecycle: z.string(),
    id: z.string(),
    demo: z.union([
      z.null(),
      z.literal('leave'),
      z.literal('ruledLeave'),
      z.literal('compensatory'),
      z.literal('trip'),
      z.literal('purchaseChain'),
      z.literal('purchase'),
      z.literal('committee'),
      z.literal('contract'),
      z.literal('contractReview'),
      z.literal('contractFullReview'),
      z.literal('countersign'),
      z.literal('legalReview'),
      z.literal('counsel'),
      z.literal('matter'),
      z.literal('reimbursement'),
      z.literal('expense'),
      z.literal('payment'),
      z.literal('financeFirst'),
      z.literal('financeAny'),
      z.literal('pool'),
      z.literal('paymentApproval'),
      z.literal('grantRequest'),
      z.literal('supplier'),
      z.literal('onboarding'),
      z.literal('launch'),
      z.literal('notice'),
      z.literal('order'),
    ]),
    business: z.union([
      z.null(),
      z.literal('leave'),
      z.literal('purchase'),
      z.literal('contract'),
      z.literal('reimbursement'),
      z.literal('payment'),
      z.literal('supplier'),
      z.literal('onboarding'),
      z.literal('launch'),
      z.literal('notice'),
      z.literal('order'),
      z.literal('travel'),
      z.literal('grant'),
    ]),
    title: z.union([z.null(), z.string()]),
    status: z.string(),
    applicantId: z.union([z.null(), z.string()]),
    parent: z.union([
      z.null(),
      z.object({ lifecycle: z.string(), id: z.string() }),
    ]),
    createdAt: z.union([z.null(), z.string()]),
    changedAt: z.union([z.null(), z.string()]),
    handlers: z.array(z.string()),
    stage: z.union([z.null(), z.string()]),
    facts: z.record(z.string(), z.json()),
  })
  .meta({ ref: 'ApprovalExampleRecordSummary' });
