import type { SettingsModuleDefinition } from './types';

export const settingsModules: readonly SettingsModuleDefinition[] = [
  {
    id: 'app-runtime',
    title: 'App 与运行时',
    description: '管理 App 身份、运行模式、域名和基础运行参数。',
    scope: 'hub',
    category: 'application',
    status: 'planned',
    capabilities: ['App 基本信息', '运行模式', '域名与入口'],
    permission: 'hub.settings.app-runtime.manage',
    configVersion: 1,
    applyMode: 'restart',
  },
  {
    id: 'release-management',
    title: '发布与恢复',
    description: '管理 Release、健康门禁、版本切换和回滚点。',
    scope: 'hub',
    category: 'operations',
    status: 'available',
    capabilities: ['受控发布', '运行状态', '版本回滚'],
    permission: 'hub.deployments.manage',
    configVersion: 1,
    applyMode: 'immediate',
    path: '/deployments',
  },
  {
    id: 'configuration-audit',
    title: '配置变更记录',
    description: '记录谁在什么时候修改了什么，以及配置应用结果。',
    scope: 'hub',
    category: 'operations',
    status: 'planned',
    capabilities: ['变更记录', '敏感字段脱敏', '失败追踪'],
    permission: 'hub.settings.audit.read',
    configVersion: 1,
    applyMode: 'immediate',
  },
  {
    id: 'file-storage',
    title: '存储适配',
    description: '为 Files / Drive 配置本地文件系统或 S3 兼容存储。',
    scope: 'app',
    category: 'application',
    status: 'prototype',
    capabilities: ['本地存储', 'S3 / OSS', '公开与私有文件'],
    permission: 'app.settings.storage.manage',
    configVersion: 1,
    applyMode: 'restart',
    path: '/settings/storage',
    containsSecrets: true,
  },
  {
    id: 'authentication-security',
    title: '认证与基础安全',
    description: '配置登录方式、会话、安全策略和外部访问边界。',
    scope: 'app',
    category: 'security',
    status: 'planned',
    capabilities: ['认证方式', '会话策略', 'CORS / CSRF', '登录保护'],
    permission: 'app.settings.security.manage',
    configVersion: 1,
    applyMode: 'restart',
    containsSecrets: true,
  },
  {
    id: 'ai-services',
    title: 'AI 服务',
    description: '统一配置模型服务、凭证、额度和默认模型。',
    scope: 'app',
    category: 'integration',
    status: 'planned',
    capabilities: ['模型服务', '密钥管理', '用量与限额'],
    permission: 'app.settings.ai.manage',
    configVersion: 1,
    applyMode: 'immediate',
    containsSecrets: true,
    supportsConnectionTest: true,
  },
  {
    id: 'notifications',
    title: '通知',
    description: '配置站内信、SMTP 及飞书、钉钉等企业通知通道。',
    scope: 'app',
    category: 'integration',
    status: 'planned',
    capabilities: ['站内信', 'SMTP', '企业通知通道', '发送测试'],
    permission: 'app.settings.notifications.manage',
    configVersion: 1,
    applyMode: 'immediate',
    containsSecrets: true,
    supportsConnectionTest: true,
  },
  {
    id: 'api-webhooks',
    title: 'API 与 Webhook',
    description: '管理开放接口凭证、回调地址、签名和重试策略。',
    scope: 'app',
    category: 'integration',
    status: 'planned',
    capabilities: ['API Token', 'Webhook', '签名与重试'],
    permission: 'app.settings.integrations.manage',
    configVersion: 1,
    applyMode: 'immediate',
    containsSecrets: true,
    supportsConnectionTest: true,
  },
  {
    id: 'user-preferences',
    title: '个人偏好',
    description: '管理语言、通知偏好、个人 Token 和 Agent 偏好。',
    scope: 'user',
    category: 'personal',
    status: 'planned',
    capabilities: ['语言与时区', '通知偏好', 'Agent 偏好'],
    permission: 'user.settings.update',
    configVersion: 1,
    applyMode: 'immediate',
  },
];

export function groupSettingsModulesByScope(
  modules: readonly SettingsModuleDefinition[],
): Record<SettingsModuleDefinition['scope'], SettingsModuleDefinition[]> {
  return modules.reduce<
    Record<SettingsModuleDefinition['scope'], SettingsModuleDefinition[]>
  >(
    (groups, module) => {
      groups[module.scope].push(module);
      return groups;
    },
    { hub: [], app: [], user: [] },
  );
}
