import { randomBytes } from 'node:crypto';
import type { DatabaseConfig } from './database.ts';

/**
 * The keys this file owns. Kept in sync with `MANAGED_ENV_KEYS` in `@nocobase/app-plugin-install`, which writes the
 * same set from the browser-based installer — the two paths must produce an equivalent `.env` or an app configured one
 * way would behave differently from one configured the other.
 */
const MANAGED_ENV_KEYS: readonly string[] = [
  'DB_DIALECT',
  'DB_DATABASE',
  'DB_DEBUG',
  'DB_HOST',
  'DB_PORT',
  'DB_USERNAME',
  'DB_PASSWORD',
  'DB_CHARSET',
  'DB_SSL',
  'DB_SCHEMA',
  'AUTH_SECRET',
];

export function generateAuthSecret(): string {
  return randomBytes(32).toString('base64url');
}

export interface BuildEnvFileOptions {
  database: DatabaseConfig;
  /** Contents of the template's `.env.example`, whose non-database lines are carried over verbatim. */
  template?: string;
  authSecret?: string;
}

/**
 * Builds the contents of `.env.local`.
 *
 * The template's `.env.example` supplies everything unrelated to the database — `APP_BASE_PATH`, migration toggles,
 * comments — and the database block is appended below it. Lines that would collide with a key written here are
 * dropped, so a value set by the user answering prompts always wins over the example's default.
 */
export function buildEnvFile(options: BuildEnvFileOptions): string {
  const secret = options.authSecret ?? generateAuthSecret();
  const values = buildEnvValues(options.database, secret);
  const preserved = dropOrphanedComments(
    (options.template ?? '').split(/\r?\n/u).filter((line) => !ownsKey(line)),
  );

  while (preserved.at(-1) === '') {
    preserved.pop();
  }

  const generated = [
    '# Generated by @nocobase/create-app.',
    ...Array.from(values, ([key, value]) => `${key}=${serializeValue(value)}`),
  ];

  return [
    ...preserved,
    ...(preserved.length > 0 ? [''] : []),
    ...generated,
    '',
  ].join('\n');
}

/**
 * Removes comment blocks left with nothing to describe.
 *
 * `.env.example` groups its keys under headings, and dropping every database key strips the body out from under
 * headings like `# Database`, leaving a run of comments followed by a blank line. Those read as a damaged file, so a
 * comment block is kept only when a setting still follows it before the next blank line.
 */
function dropOrphanedComments(lines: readonly string[]): string[] {
  const kept: string[] = [];
  let block: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith('#')) {
      block.push(line);
      continue;
    }

    // A blank line closes a block. Comments with no setting under them described keys that are gone.
    if (trimmed === '') {
      block = [];
      // Collapse the run of blank lines a removed block would otherwise leave behind.
      if (kept.at(-1) !== '') {
        kept.push(line);
      }
      continue;
    }

    kept.push(...block, line);
    block = [];
  }

  return kept;
}

function ownsKey(line: string): boolean {
  const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/u.exec(line);
  return match?.[1] !== undefined && MANAGED_ENV_KEYS.includes(match[1]);
}

export function buildEnvValues(
  database: DatabaseConfig,
  secret: string,
): ReadonlyMap<string, string> {
  const values = new Map<string, string>([
    ['DB_DIALECT', database.dialect],
    ['DB_DATABASE', database.database],
  ]);

  if (database.dialect !== 'sqlite') {
    values.set('DB_HOST', database.host);
    values.set('DB_PORT', String(database.port));
    values.set('DB_USERNAME', database.username);
    values.set('DB_PASSWORD', database.password);
  }

  if (database.dialect === 'postgres') {
    values.set('DB_SCHEMA', database.schema);
    values.set('DB_SSL', String(database.ssl));
  }

  if (database.dialect === 'mysql') {
    values.set('DB_CHARSET', database.charset);
  }

  values.set('AUTH_SECRET', secret);

  return values;
}

/**
 * Quotes only when the value would not survive a bare assignment. An empty password is written as `DB_PASSWORD=`,
 * which the template's env parser reads back as an empty string rather than as an unset key.
 */
function serializeValue(value: string): string {
  if (value === '' || /^[A-Za-z0-9_./:@,+-]+$/u.test(value)) {
    return value;
  }

  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}
