import type { Kysely, Transaction } from "kysely";
import type { FileStatus, JsonObject, UploadStatus } from "../contracts/index.ts";
import type { FilesDatabase, FileRecord, UploadRecord } from "./database-types.ts";
import { decodeJson, encodeJson, toDate, toSafeNumber } from "./serialization.ts";
import type { CreatePendingUploadInput, CreatePendingUploadResult, FilesStore, VerifiedObject } from "./files-store.ts";

const conflict = (): never => { throw new Error("FILES_IDEMPOTENCY_KEY_REUSED"); };
const invalid = (): never => { throw new Error("Invalid state transition"); };
const transitions = {
  file: { pending: ["ready", "failed", "deleted"], ready: ["deleted"], failed: ["deleted"], deleted: ["deleted"] },
  upload: { pending: ["completed", "failed", "expired"], completed: ["completed"], failed: [], expired: [] },
} satisfies { file: Record<FileStatus, FileStatus[]>; upload: Record<UploadStatus, UploadStatus[]> };
const assertTransition = <T extends "file" | "upload">(type: T, from: T extends "file" ? FileStatus : UploadStatus, to: T extends "file" ? FileStatus : UploadStatus) => {
  if (!(transitions[type] as Record<string, string[]>)[from].includes(to)) invalid();
};
const rowFile = (r: FilesDatabase["files"]): FileRecord => ({ id: r.id, workspaceId: r.workspace_id, backendKey: r.backend_key, policy: r.policy, storageKey: r.storage_key, originalName: r.original_name, contentType: r.content_type, size: toSafeNumber(r.size), ...(r.checksum_sha256 ? { checksumSha256: r.checksum_sha256 } : {}), status: r.status, ...(r.access_context_json ? { accessContext: decodeJson(r.access_context_json) } : {}), createdBy: r.created_by, createdAt: toDate(r.created_at), updatedAt: toDate(r.updated_at), ...(r.deleted_at ? { deletedAt: toDate(r.deleted_at) } : {}), storageDeleteStatus: r.storage_delete_status, ...(r.storage_deleted_at ? { storageDeletedAt: toDate(r.storage_deleted_at) } : {}) });
const rowUpload = (r: FilesDatabase["file_uploads"]): UploadRecord => ({ id: r.id, workspaceId: r.workspace_id, fileId: r.file_id, createdBy: r.created_by, idempotencyKey: r.idempotency_key, requestFingerprint: r.request_fingerprint, status: r.status, expiresAt: toDate(r.expires_at), ...(r.provider_state_json ? { providerState: decodeJson(r.provider_state_json) } : {}), createdAt: toDate(r.created_at), ...(r.completed_at ? { completedAt: toDate(r.completed_at) } : {}) });
type Db = Kysely<FilesDatabase> | Transaction<FilesDatabase>;

export class KyselyFilesStore implements FilesStore {
  constructor(private readonly db: Kysely<FilesDatabase>, private readonly now = () => new Date()) {}
  async createPendingUpload(input: CreatePendingUploadInput): Promise<CreatePendingUploadResult> {
    const run = (): Promise<CreatePendingUploadResult> => this.db.transaction().execute(async tx => {
      const existing = await tx.selectFrom("file_uploads").selectAll().where("workspace_id", "=", input.file.workspaceId).where("created_by", "=", input.file.createdBy).where("idempotency_key", "=", input.upload.idempotencyKey).executeTakeFirst();
      if (existing) { if (existing.request_fingerprint !== input.upload.requestFingerprint) conflict(); const file = await tx.selectFrom("files").selectAll().where("id", "=", existing.file_id).executeTakeFirstOrThrow(); return { kind: "replayed", file: rowFile(file), upload: rowUpload(existing) }; }
      const now = this.now();
      await tx.insertInto("files").values({ id: input.file.id, workspace_id: input.file.workspaceId, backend_key: input.file.backendKey, policy: input.file.policy, storage_key: input.file.storageKey, original_name: input.file.originalName, content_type: input.file.contentType, size: input.file.size, checksum_sha256: input.file.checksumSha256 ?? null, status: "pending", access_context_json: encodeJson(input.file.accessContext), created_by: input.file.createdBy, created_at: now, updated_at: now, deleted_at: null, storage_delete_status: "pending", storage_deleted_at: null }).execute();
      await tx.insertInto("file_uploads").values({ id: input.upload.id, workspace_id: input.file.workspaceId, file_id: input.file.id, created_by: input.file.createdBy, idempotency_key: input.upload.idempotencyKey, request_fingerprint: input.upload.requestFingerprint, status: "pending", expires_at: input.upload.expiresAt, provider_state_json: encodeJson(input.upload.providerState), created_at: now, completed_at: null }).execute();
      return { kind: "created", file: rowFile(await tx.selectFrom("files").selectAll().where("id", "=", input.file.id).executeTakeFirstOrThrow()), upload: rowUpload(await tx.selectFrom("file_uploads").selectAll().where("id", "=", input.upload.id).executeTakeFirstOrThrow()) };
    });
    try { return await run(); } catch (error) {
      const existing = await this.db.selectFrom("file_uploads").selectAll().where("workspace_id", "=", input.file.workspaceId).where("created_by", "=", input.file.createdBy).where("idempotency_key", "=", input.upload.idempotencyKey).executeTakeFirst();
      if (!existing) throw error;
      if (existing.request_fingerprint !== input.upload.requestFingerprint) conflict();
      const file = await this.db.selectFrom("files").selectAll().where("id", "=", existing.file_id).executeTakeFirstOrThrow();
      return { kind: "replayed", file: rowFile(file), upload: rowUpload(existing) };
    }
  }
  async getFile(workspaceId: string, fileId: string, options?: { includeDeleted?: boolean }) { let q = this.db.selectFrom("files").selectAll().where("workspace_id", "=", workspaceId).where("id", "=", fileId); if (!options?.includeDeleted) q = q.where("status", "!=", "deleted"); const r = await q.executeTakeFirst(); return r && rowFile(r); }
  async getUpload(workspaceId: string, uploadId: string) { const r = await this.db.selectFrom("file_uploads").selectAll().where("workspace_id", "=", workspaceId).where("id", "=", uploadId).executeTakeFirst(); return r && rowUpload(r); }
  async updateUploadProviderState(workspaceId: string, uploadId: string, expectedStatus: "pending", state: JsonObject) { const r = await this.db.updateTable("file_uploads").set({ provider_state_json: encodeJson(state) }).where("workspace_id", "=", workspaceId).where("id", "=", uploadId).where("status", "=", expectedStatus).returningAll().executeTakeFirst(); if (!r) invalid(); return rowUpload(r as FilesDatabase["file_uploads"]); }
  async completeUpload(workspaceId: string, uploadId: string, verified: VerifiedObject) { return this.db.transaction().execute(async tx => { const u = await tx.selectFrom("file_uploads").selectAll().where("workspace_id", "=", workspaceId).where("id", "=", uploadId).executeTakeFirstOrThrow(); const f = await tx.selectFrom("files").selectAll().where("id", "=", u.file_id).where("workspace_id", "=", workspaceId).executeTakeFirstOrThrow(); if (u.status === "completed") return rowFile(f); assertTransition("upload", u.status, "completed"); assertTransition("file", f.status, "ready"); const now = this.now(); await tx.updateTable("file_uploads").set({ status: "completed", completed_at: now }).where("id", "=", uploadId).execute(); return rowFile(await tx.updateTable("files").set({ status: "ready", content_type: verified.contentType, size: verified.size, checksum_sha256: verified.checksumSha256 ?? null, updated_at: now }).where("id", "=", f.id).returningAll().executeTakeFirstOrThrow()); }); }
  async failUpload(workspaceId: string, uploadId: string, _reason?: JsonObject) { return this.db.transaction().execute(async tx => { const u = await tx.selectFrom("file_uploads").selectAll().where("workspace_id", "=", workspaceId).where("id", "=", uploadId).executeTakeFirstOrThrow(); assertTransition("upload", u.status, "failed"); const f = await tx.selectFrom("files").selectAll().where("id", "=", u.file_id).executeTakeFirstOrThrow(); assertTransition("file", f.status, "failed"); await tx.updateTable("file_uploads").set({ status: "failed" }).where("id", "=", uploadId).execute(); await tx.updateTable("files").set({ status: "failed", updated_at: this.now() }).where("id", "=", u.file_id).execute(); return rowUpload(await tx.selectFrom("file_uploads").selectAll().where("id", "=", uploadId).executeTakeFirstOrThrow()); }); }
  async listExpiredPendingUploads(now: Date, limit: number) { const rs = await this.db.selectFrom("file_uploads").selectAll().where("status", "=", "pending").where("expires_at", "<=", now).orderBy("expires_at").orderBy("id").limit(limit).execute(); return rs.map(rowUpload); }
  async expireUpload(workspaceId: string, uploadId: string, now: Date) { return this.db.transaction().execute(async tx => { const u = await tx.selectFrom("file_uploads").selectAll().where("workspace_id", "=", workspaceId).where("id", "=", uploadId).executeTakeFirstOrThrow(); assertTransition("upload", u.status, "expired"); if (toDate(u.expires_at) > now) invalid(); const f = await tx.selectFrom("files").selectAll().where("id", "=", u.file_id).executeTakeFirstOrThrow(); assertTransition("file", f.status, "failed"); await tx.updateTable("file_uploads").set({ status: "expired" }).where("id", "=", uploadId).execute(); await tx.updateTable("files").set({ status: "failed", updated_at: now }).where("id", "=", u.file_id).execute(); return rowUpload(await tx.selectFrom("file_uploads").selectAll().where("id", "=", uploadId).executeTakeFirstOrThrow()); }); }
  async markFileDeleted(workspaceId: string, fileId: string, _actorId: string, now: Date) { const f = await this.db.selectFrom("files").selectAll().where("workspace_id", "=", workspaceId).where("id", "=", fileId).executeTakeFirstOrThrow(); assertTransition("file", f.status, "deleted"); if (f.status === "deleted") return rowFile(f); return rowFile(await this.db.updateTable("files").set({ status: "deleted", deleted_at: now, updated_at: now, storage_delete_status: "pending" }).where("id", "=", fileId).returningAll().executeTakeFirstOrThrow()); }
  async listFilesPendingPhysicalDelete(limit: number) { const rs = await this.db.selectFrom("files").selectAll().where("status", "=", "deleted").where("storage_delete_status", "=", "pending").orderBy("deleted_at").orderBy("id").limit(limit).execute(); return rs.map(rowFile); }
  async markPhysicalDeleteCompleted(workspaceId: string, fileId: string, now: Date) { const r = await this.db.updateTable("files").set({ storage_delete_status: "completed", storage_deleted_at: now }).where("workspace_id", "=", workspaceId).where("id", "=", fileId).where("status", "=", "deleted").returningAll().executeTakeFirst(); if (!r) invalid(); return rowFile(r as FilesDatabase["files"]); }
}
