import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  createReleaseContract,
  stableJson,
  verifyReleaseContract,
} from './lib/release-contract.mjs';

const scriptPath = fileURLToPath(import.meta.url);
const defaultAppRoot = path.resolve(path.dirname(scriptPath), '..');
const defaultWorkspaceRoot = path.resolve(defaultAppRoot, '../..');

export function createReleaseArtifact({
  appRoot = defaultAppRoot,
  outputRoot = path.join(defaultWorkspaceRoot, 'app-dist'),
  releaseId,
  nocoBaseApiUrl,
  createdAt = new Date().toISOString(),
}) {
  const normalizedReleaseId = requireSafeSegment(releaseId, 'release id');
  const resolvedAppRoot = path.resolve(appRoot);
  const resolvedOutputRoot = path.resolve(outputRoot);
  const distRoot = path.join(resolvedAppRoot, 'dist');
  const config = readJson(
    path.join(resolvedAppRoot, 'app-release.config.json'),
  );
  const sourcePackage = readJson(path.join(resolvedAppRoot, 'package.json'));
  const appId = requireSafeSegment(config.appId, 'app id');
  const dataRuntime = normalizeDataRuntime(config.dataRuntime);
  const normalizedApiUrl =
    dataRuntime === 'native' ? undefined : normalizeApiUrl(nocoBaseApiUrl);
  const packageName = requireText(sourcePackage.name, 'package name');
  const version = requireText(sourcePackage.version, 'package version');
  const healthPath = requireHealthPath(config.healthPath ?? '/healthz');
  const runtime = normalizeRuntime(config.runtime, healthPath);
  const requiredCollections = normalizeRequiredCollections(
    config.requiredCollections,
  );
  const preparedContract = createReleaseContract(resolvedAppRoot);
  const contractContent = `${JSON.stringify(preparedContract.contract, null, 2)}\n`;
  const contractRelativePath = 'server/release-contract.json';

  requireFile(path.join(distRoot, 'server', 'embedded.js'));
  requireFile(path.join(distRoot, 'client', 'index.html'));
  if (fs.existsSync(path.join(distRoot, ...contractRelativePath.split('/')))) {
    throw new Error(
      `${contractRelativePath} is generated by release packaging and must not exist in source dist`,
    );
  }

  const artifactSha256 = hashDirectoryWithFile(
    distRoot,
    contractRelativePath,
    contractContent,
  );
  const manifestBase = {
    schemaVersion: 1,
    appId,
    releaseId: normalizedReleaseId,
    version,
    artifactSha256,
    runtime,
  };
  const releasePackage = {
    name: packageName,
    version,
    private: true,
    type: 'module',
    app: {
      enabled: true,
      appName: appId,
      backend: runtime.backend,
      isolation: runtime.isolation,
      tier: runtime.tier,
      version,
      healthPath,
      resourcePolicy: runtime.resourcePolicy,
      config: {
        dataRuntime,
        ...(normalizedApiUrl ? { nocoBaseApiUrl: normalizedApiUrl } : {}),
      },
    },
  };
  const releaseFingerprint = sha256(
    stableJson({
      artifactSha256,
      manifest: manifestBase,
      package: releasePackage,
      requiredCollections,
      contractSha256: preparedContract.contractSha256,
      dataRuntime,
      nocoBaseApiUrl: normalizedApiUrl,
    }),
  );
  const releaseRoot = resolveReleaseRoot(
    resolvedOutputRoot,
    appId,
    normalizedReleaseId,
  );

  if (fs.existsSync(releaseRoot)) {
    assertExistingReleaseMatches({
      releaseRoot,
      manifestBase,
      releasePackage,
      artifactSha256,
      releaseFingerprint,
      requiredCollections,
      contractSha256: preparedContract.contractSha256,
      dataRuntime,
      nocoBaseApiUrl: normalizedApiUrl,
    });
    return {
      status: 'unchanged',
      appId,
      releaseId: normalizedReleaseId,
      version,
      releaseRoot,
      artifactSha256,
      contractSha256: preparedContract.contractSha256,
    };
  }

  const releasesRoot = path.dirname(releaseRoot);
  fs.mkdirSync(releasesRoot, { recursive: true });
  const stagingRoot = fs.mkdtempSync(
    path.join(releasesRoot, `.${normalizedReleaseId}-`),
  );

  try {
    fs.cpSync(distRoot, path.join(stagingRoot, 'dist'), {
      recursive: true,
      errorOnExist: true,
      force: false,
      preserveTimestamps: true,
    });
    fs.writeFileSync(
      path.join(stagingRoot, 'dist', ...contractRelativePath.split('/')),
      contractContent,
      {
        flag: 'wx',
      },
    );
    const stagedArtifactSha256 = hashDirectory(path.join(stagingRoot, 'dist'));
    if (stagedArtifactSha256 !== artifactSha256) {
      throw new Error(
        `Staged artifact checksum mismatch: expected ${artifactSha256}, received ${stagedArtifactSha256}`,
      );
    }
    writeJson(path.join(stagingRoot, 'package.json'), releasePackage);
    writeJson(path.join(stagingRoot, 'app-release.json'), {
      ...manifestBase,
      createdAt: new Date(createdAt).toISOString(),
    });
    writeJson(path.join(stagingRoot, 'release-metadata.json'), {
      schemaVersion: 1,
      appId,
      releaseId: normalizedReleaseId,
      version,
      nocoBaseApiUrl: normalizedApiUrl,
      requiredCollections,
      contractSha256: preparedContract.contractSha256,
      dataRuntime,
      artifactSha256,
      releaseFingerprint,
    });
    fs.renameSync(stagingRoot, releaseRoot);
  } catch (error) {
    fs.rmSync(stagingRoot, { recursive: true, force: true });
    throw error;
  }

  return {
    status: 'created',
    appId,
    releaseId: normalizedReleaseId,
    version,
    releaseRoot,
    artifactSha256,
    contractSha256: preparedContract.contractSha256,
  };
}

export function hashDirectory(root) {
  const resolvedRoot = path.resolve(root);
  const hash = createHash('sha256');
  for (const file of listFiles(resolvedRoot)) {
    updateArtifactHash(
      hash,
      path.relative(resolvedRoot, file).split(path.sep).join('/'),
      fs.readFileSync(file),
    );
  }
  return hash.digest('hex');
}

export function createVerifiedReleaseArtifact({
  targetEnv,
  confirmCrossEnv = false,
  runNb,
  ...options
}) {
  const appRoot = options.appRoot ?? defaultAppRoot;
  const config = readJson(
    path.join(path.resolve(appRoot), 'app-release.config.json'),
  );
  const dataRuntime = normalizeDataRuntime(config.dataRuntime);
  if (dataRuntime === 'native') {
    const prepared = createReleaseContract(appRoot);
    return {
      ...createReleaseArtifact({ ...options, appRoot }),
      verification: {
        schemaVersion: 1,
        mode: 'native',
        contractSha256: prepared.contractSha256,
        database: 'release-owned',
      },
    };
  }
  const verification = verifyReleaseContract({
    appRoot,
    targetEnv,
    apiBaseUrl: options.nocoBaseApiUrl,
    confirmCrossEnv,
    runNb,
  });
  return {
    ...createReleaseArtifact(options),
    verification,
  };
}

function assertExistingReleaseMatches({
  releaseRoot,
  manifestBase,
  releasePackage,
  artifactSha256,
  releaseFingerprint,
  requiredCollections,
  contractSha256,
  dataRuntime,
  nocoBaseApiUrl,
}) {
  const existingManifest = readJson(path.join(releaseRoot, 'app-release.json'));
  const existingPackage = readJson(path.join(releaseRoot, 'package.json'));
  const existingMetadata = readJson(
    path.join(releaseRoot, 'release-metadata.json'),
  );
  const existingArtifactSha256 = hashDirectory(path.join(releaseRoot, 'dist'));
  const existingManifestBase = { ...existingManifest };
  delete existingManifestBase.createdAt;
  const matches =
    stableJson(existingManifestBase) === stableJson(manifestBase) &&
    stableJson(existingPackage) === stableJson(releasePackage) &&
    stableJson(existingMetadata.requiredCollections) ===
      stableJson(requiredCollections) &&
    existingMetadata.contractSha256 === contractSha256 &&
    existingMetadata.dataRuntime === dataRuntime &&
    existingMetadata.nocoBaseApiUrl === nocoBaseApiUrl &&
    existingMetadata.artifactSha256 === artifactSha256 &&
    existingMetadata.releaseFingerprint === releaseFingerprint &&
    existingArtifactSha256 === artifactSha256;

  if (!matches) {
    throw new Error(
      `Release ${manifestBase.appId}/${manifestBase.releaseId} already exists with different contents. ` +
        'Release directories are immutable; choose a new release id.',
    );
  }
}

function resolveReleaseRoot(outputRoot, appId, releaseId) {
  const releaseRoot = path.resolve(outputRoot, appId, 'releases', releaseId);
  const relative = path.relative(outputRoot, releaseRoot);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error(`Release path must stay inside ${outputRoot}`);
  }
  return releaseRoot;
}

function normalizeRuntime(value, healthPath) {
  const runtime =
    value && typeof value === 'object' && !Array.isArray(value) ? value : {};
  return {
    backend: runtime.backend ?? 'in-process',
    isolation: runtime.isolation ?? 'in-process',
    tier: runtime.tier ?? 'warm',
    healthPath,
    resourcePolicy: runtime.resourcePolicy,
  };
}

function normalizeRequiredCollections(value) {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(
      'app-release.config.json requiredCollections must be a non-empty array',
    );
  }
  const collections = value.map((item) =>
    requireSafeSegment(item, 'required collection'),
  );
  if (new Set(collections).size !== collections.length) {
    throw new Error(
      'app-release.config.json requiredCollections must not contain duplicates',
    );
  }
  return collections;
}

function normalizeApiUrl(value) {
  const text = requireText(value, 'NocoBase API URL');
  const url = new URL(text);
  if (!['http:', 'https:'].includes(url.protocol)) {
    throw new Error('NocoBase API URL must use http or https');
  }
  return url.toString().replace(/\/$/, '');
}

function normalizeDataRuntime(value) {
  const mode = value ?? 'nocobase';
  if (mode !== 'native' && mode !== 'nocobase') {
    throw new Error('dataRuntime must be native or nocobase');
  }
  return mode;
}

function requireHealthPath(value) {
  const healthPath = requireText(value, 'health path');
  if (
    !healthPath.startsWith('/') ||
    healthPath.startsWith('//') ||
    healthPath.includes('?') ||
    healthPath.includes('#')
  ) {
    throw new Error(
      'health path must be absolute and must not contain a query or hash',
    );
  }
  return healthPath;
}

function requireSafeSegment(value, label) {
  const segment = requireText(value, label);
  if (
    !/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$/.test(segment) ||
    segment === '.' ||
    segment === '..'
  ) {
    throw new Error(`${label} must be a safe path segment`);
  }
  return segment;
}

function requireText(value, label) {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`${label} is required`);
  }
  return value.trim();
}

function requireFile(file) {
  if (!fs.statSync(file, { throwIfNoEntry: false })?.isFile()) {
    throw new Error(`Missing release input: ${file}`);
  }
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeJson(file, value) {
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx' });
}

function listFiles(root) {
  if (!fs.statSync(root, { throwIfNoEntry: false })?.isDirectory()) {
    throw new Error(`Missing release directory: ${root}`);
  }
  const files = [];
  const visit = (directory) => {
    const entries = fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      const entryPath = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) {
        throw new Error(
          `Release input must not contain symbolic links: ${entryPath}`,
        );
      }
      if (entry.isDirectory()) {
        visit(entryPath);
      } else if (entry.isFile()) {
        files.push(entryPath);
      }
    }
  };
  visit(root);
  return files;
}

function sha256(value) {
  return createHash('sha256').update(value).digest('hex');
}

function parseArguments(argv) {
  const allowed = new Set([
    'release-id',
    'nocobase-api-url',
    'output-root',
    'env',
    'yes',
  ]);
  const values = {};
  for (let index = 0; index < argv.length; index += 1) {
    const name = argv[index];
    if (!name?.startsWith('--')) {
      throw new Error(`Unknown argument: ${name}`);
    }
    if (!allowed.has(name.slice(2))) {
      throw new Error(`Unknown argument: ${name}`);
    }
    if (name === '--yes') {
      values.yes = true;
      continue;
    }
    const value = argv[index + 1];
    if (!value || value.startsWith('--')) {
      throw new Error(`Missing value for ${name}`);
    }
    values[name.slice(2)] = value;
    index += 1;
  }
  return values;
}

function main() {
  const args = parseArguments(process.argv.slice(2));
  const result = createVerifiedReleaseArtifact({
    releaseId: args['release-id'],
    nocoBaseApiUrl: args['nocobase-api-url'],
    outputRoot: args['output-root']
      ? path.resolve(args['output-root'])
      : undefined,
    targetEnv: args.env,
    confirmCrossEnv: args.yes === true,
  });
  console.log(JSON.stringify(result, null, 2));
}

function hashDirectoryWithFile(root, relativePath, content) {
  const resolvedRoot = path.resolve(root);
  const hash = createHash('sha256');
  const virtualDirectory = path.posix.dirname(relativePath);
  const virtualName = path.posix.basename(relativePath);
  let virtualFileVisited = false;

  const visit = (directory, relativeDirectory = '') => {
    const entries = fs
      .readdirSync(directory, { withFileTypes: true })
      .map((entry) => ({ entry }));
    if (relativeDirectory === virtualDirectory) {
      entries.push({ virtualName });
    }
    entries.sort((left, right) =>
      (left.entry?.name ?? left.virtualName).localeCompare(
        right.entry?.name ?? right.virtualName,
      ),
    );

    for (const item of entries) {
      if (item.virtualName) {
        virtualFileVisited = true;
        updateArtifactHash(hash, relativePath, Buffer.from(content));
        continue;
      }
      const entry = item.entry;
      const entryPath = path.join(directory, entry.name);
      const entryRelative = relativeDirectory
        ? `${relativeDirectory}/${entry.name}`
        : entry.name;
      if (entry.isSymbolicLink()) {
        throw new Error(
          `Release input must not contain symbolic links: ${entryPath}`,
        );
      }
      if (entry.isDirectory()) {
        visit(entryPath, entryRelative);
      } else if (entry.isFile()) {
        updateArtifactHash(hash, entryRelative, fs.readFileSync(entryPath));
      }
    }
  };

  visit(resolvedRoot);
  if (!virtualFileVisited) {
    throw new Error(
      `Generated release contract directory is missing: ${virtualDirectory}`,
    );
  }
  return hash.digest('hex');
}

function updateArtifactHash(hash, relativePath, content) {
  hash.update(relativePath);
  hash.update('\0');
  hash.update(content);
  hash.update('\0');
}

if (process.argv[1] && path.resolve(process.argv[1]) === scriptPath) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
