import { createRequire } from 'node:module';
import type {
  ConnectionConfig,
  DatabaseCapabilities,
  DatabaseDriverDefinition,
  OracleConnectionConfig,
} from '@nocobase/db';
import { rawRows } from '@nocobase/db';
import { preciseIntegerClient } from './precise-integers.js';
import { OracleSchemaInspector } from './inspectors/oracle.js';

const require = createRequire(import.meta.url);
const Oracledb: unknown = require('oracledb') as unknown;
export type OracleOptions = Omit<
  OracleConnectionConfig,
  'dialect' | 'driver' | 'databaseDriver'
>;
export const oracleDriver: DatabaseDriverDefinition<'oracle'> = {
  dialect: 'oracle',
  packageName: '@nocobase/db-oracle',
  nativeDriver: 'oracledb',
  knexClient: 'oracledb',
  resolveKnexClient: () =>
    require('knex/lib/dialects/oracledb/index.js') as typeof import('knex').Knex.Client,
  capabilities: {
    schemas: true,
    materializedViews: true,
    refreshMaterializedViews: true,
    deferrableConstraints: true,
    nativeTypes: true,
    comments: true,
  } satisfies Partial<DatabaseCapabilities>,
  createRuntime: ({ dialect, capabilities }) => ({
    dialect,
    capabilities,
    numeric: {
      aggregateProjection: ({ client, expression }) =>
        client.raw(`to_char(?, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''')`, [
          expression,
        ]),
    },
    schema: {
      assertExecutable: (operations) => {
        for (const operation of operations) {
          if (operation.type !== 'createTable') continue;
          const restricted = new Set(
            operation.table.columns
              .filter(
                (column) =>
                  column.type === 'datetimeTz' ||
                  /^timestamp(?:\(\d+\))? with time zone$/i.test(
                    column.db?.nativeType ?? '',
                  ),
              )
              .map((column) => column.name),
          );
          if (
            operation.table.columns.some(
              (column) => restricted.has(column.name) && column.primaryKey,
            ) ||
            operation.table.constraints.some(
              (constraint) =>
                (constraint.type === 'primary' ||
                  constraint.type === 'unique') &&
                constraint.columns.some((column) => restricted.has(column)),
            )
          )
            throw new Error(
              'Oracle TIMESTAMP WITH TIME ZONE columns cannot be primary or unique keys.',
            );
        }
      },
      dropIndexOperation: (error) => {
        if (!error || typeof error !== 'object') return false;
        const candidate = error as { errorNum?: unknown; message?: unknown };
        return (
          candidate.errorNum === 2429 ||
          (typeof candidate.message === 'string' &&
            candidate.message.includes('ORA-02429'))
        );
      },
      normalizeOperation: async (operation, client) => {
        if (operation.type !== 'alterTable') return operation;
        const operations = [];
        for (const item of operation.operations) {
          if (
            item.type !== 'alterColumn' ||
            !['char', 'enum'].includes(String(item.changes.type)) ||
            item.changes.nullable === undefined
          ) {
            operations.push(item);
            continue;
          }
          const result: unknown = await client.raw(
            "select nullable from all_tab_columns where owner = coalesce(?, sys_context('USERENV', 'CURRENT_SCHEMA')) and table_name = ? and column_name = ?",
            [operation.db?.schema ?? null, operation.tableName, item.column],
          );
          const rows = Array.isArray(result)
            ? (result as Array<{ NULLABLE: string }>)
            : [];
          const changes = { ...item.changes };
          if (rows[0] && (rows[0].NULLABLE === 'Y') === changes.nullable)
            delete changes.nullable;
          operations.push({ ...item, changes });
        }
        return { ...operation, operations };
      },
      columnType: ({ column }) => {
        // Oracle 12c+ supports identity columns directly. Do not delegate
        // auto-increment columns to Knex's legacy sequence/trigger compiler:
        // its trigger looks up the primary key from the data dictionary
        // before the table DDL has made that metadata visible.
        if (column.autoIncrement || column.type === 'increments') {
          return `${
            column.type === 'bigInt' ? 'number(20, 0)' : 'integer'
          } generated by default as identity`;
        }
        if (column.type === 'integer') return 'number(9, 0)';
        if (column.type === 'bigInt') return 'number(18, 0)';
        if (column.type === 'enum')
          return `varchar2(${column.length ?? 255} char)`;
        if (column.type === 'char') return `char(${column.length ?? 255} char)`;
        if (column.type === 'float') return 'binary_float';
        if (column.type === 'double') return 'binary_double';
        if (column.type === 'time') return 'varchar2(18)';
        if (column.type === 'datetime') return 'timestamp(3)';
        if (column.type === 'datetimeTz') return 'timestamp(3) with time zone';
        return undefined;
      },
      configureForeignKey: ({ foreign, constraint }) => {
        const builder = foreign as { onDelete(action: string): unknown };
        if (
          constraint.onDelete === 'cascade' ||
          constraint.onDelete === 'set null'
        )
          builder.onDelete(constraint.onDelete.toUpperCase());
      },
    },
    repository: {
      enumGroupKey: ({ client, field }) =>
        client.raw('utl_raw.cast_to_raw(??)', [field]),
      compileFilterCondition: ({ query, node, field, name, boolean }) => {
        if (
          (field?.type === 'text' || field?.type === 'string') &&
          node.operator === '$empty'
        ) {
          query[boolean === 'or' ? 'orWhereNull' : 'whereNull'](name);
          return { handled: true };
        }
        if (
          (field?.type === 'text' || field?.type === 'string') &&
          node.operator === '$notEmpty'
        ) {
          query[boolean === 'or' ? 'orWhereNotNull' : 'whereNotNull'](name);
          return { handled: true };
        }
        if (
          field?.type === 'text' &&
          typeof node.value === 'string' &&
          (node.operator === '$eq' || node.operator === '$ne')
        ) {
          query[boolean === 'or' ? 'orWhereRaw' : 'whereRaw'](
            `dbms_lob.compare(??, to_clob(?)) ${node.operator === '$eq' ? '=' : '<>'} 0`,
            [name, node.value],
          );
          return { handled: true };
        }
        if (
          (field?.type === 'enum' || field?.type === 'char') &&
          typeof node.value === 'string' &&
          (node.operator === '$eq' || node.operator === '$ne')
        ) {
          const expression =
            field.type === 'char'
              ? `rtrim(??) ${node.operator === '$eq' ? '=' : '<>'} rtrim(?)`
              : `utl_raw.cast_to_raw(??) ${node.operator === '$eq' ? '=' : '<>'} utl_raw.cast_to_raw(?)`;
          query[boolean === 'or' ? 'orWhereRaw' : 'whereRaw'](expression, [
            name,
            node.value,
          ]);
          return { handled: true };
        }
        return { handled: false };
      },
      bindValue: ({ client, field, value }) => {
        if (field.type !== 'char' || typeof value !== 'string')
          return undefined;
        return client.raw(`cast(? as char(${field.length ?? 1}))`, [value]);
      },
      streamOptions: () => ({
        outFormat: (Oracledb as { OUT_FORMAT_OBJECT: number })
          .OUT_FORMAT_OBJECT,
      }),
      decodeStreamRow: async (row) => {
        const driver = Oracledb as { CLOB: object; NCLOB: object };
        for (const [field, value] of Object.entries(row)) {
          if (
            !value ||
            typeof value !== 'object' ||
            !(Symbol.asyncIterator in value)
          )
            continue;
          const lob = value as AsyncIterable<Buffer> & { type?: object };
          const textual = lob.type === driver.CLOB || lob.type === driver.NCLOB;
          const chunks: Buffer[] = [];
          for await (const chunk of lob) chunks.push(Buffer.from(chunk));
          row[field] = textual
            ? Buffer.concat(chunks).toString('utf8')
            : Buffer.concat(chunks);
        }
        return row;
      },
      createManyFallback: (collection) =>
        collection.fields?.some(
          (field) =>
            !('target' in field) &&
            ['date', 'time', 'datetime', 'datetimeTz'].includes(field.type),
        ) ?? false,
      emptyInsertValue: ({ client, collection, column }) => {
        const field = collection.fields?.find(
          (item) => !('target' in item) && item.db?.generated === undefined,
        );
        return field
          ? {
              [column(field.name)]: client.raw('default'),
            }
          : undefined;
      },
      reloadReturnedDecimal: true,
      collectionAliasKeyword: ' ',
      limitLockedQuery: (query) => {
        query.whereRaw('rownum <= ?', [2]);
      },
      encodeBoolean: (field, value) =>
        field.db?.nativeType && /^boolean$/i.test(String(field.db.nativeType))
          ? value === null
            ? null
            : Boolean(value)
          : value === null
            ? null
            : value
              ? 1
              : 0,
      temporalBinding: ({ client, field, value }) => {
        const normalized = String(value);
        if (field.type === 'date')
          return client.raw("to_date(?, 'YYYY-MM-DD')", [normalized]);
        if (field.type === 'time') return normalized;
        const instant = field.type === 'datetimeTz';
        return instant
          ? client.raw(
              'to_timestamp_tz(?, \'YYYY-MM-DD"T"HH24:MI:SS.FF3TZH:TZM\')',
              [normalized.replace('Z', '+00:00')],
            )
          : client.raw('to_timestamp(?, \'YYYY-MM-DD"T"HH24:MI:SS.FF3\')', [
              normalized,
            ]);
      },
      temporalProjection: ({ client, field, reference }) => {
        if (!field)
          return typeof reference === 'string'
            ? client.ref(reference)
            : reference;
        if (field.type === 'time')
          return typeof reference === 'string'
            ? client.ref(reference)
            : reference;
        const instant = field.type === 'datetimeTz';
        const format =
          field.type === 'date' ? 'YYYY-MM-DD' : 'YYYY-MM-DD"T"HH24:MI:SS.FF3';
        return client.raw(
          instant
            ? `case when ?? is null then null else to_char(sys_extract_utc(??), ?) || 'Z' end`
            : field.type === 'datetime'
              ? 'to_char(cast(?? as timestamp(3)), ?)'
              : 'to_char(??, ?)',
          instant ? [reference, reference, format] : [reference, format],
        );
      },
    },
    query: {
      configureAggregateResults: ({ query, aliases }) => {
        const driver = Oracledb as {
          DB_TYPE_NUMBER: unknown;
          STRING: unknown;
        };
        query.options({
          fetchTypeHandler: (column: { name: string; dbType: unknown }) =>
            aliases.has(column.name) && column.dbType === driver.DB_TYPE_NUMBER
              ? { type: driver.STRING }
              : undefined,
        });
      },
    },
  }),
  createKnexClient: () =>
    // Oracle's integer codecs are installed by the shared Knex helper.
    preciseIntegerClient(Oracledb),
  resolveConnection: (source: ConnectionConfig) => {
    const config = source as OracleConnectionConfig;
    assertDriverOptions(config.driverOptions, [
      'host',
      'port',
      'database',
      'serviceName',
      'user',
      'username',
      'password',
      'connectString',
      'externalAuth',
      'pool',
      'url',
      'connectionString',
      'uri',
    ]);
    if (config.serviceName.trim() === '') {
      throw new Error(
        'Oracle database serviceName must be a non-empty string.',
      );
    }
    return {
      connection: compactObject({
        ...config.driverOptions,
        user: config.username,
        password: config.password,
        connectString: `${config.host ?? '127.0.0.1'}:${config.port ?? 1521}/${config.serviceName}`,
      }),
    };
  },
  createSchemaInspector: (context) =>
    new OracleSchemaInspector({
      connectionName: context.connectionName,
      resolveClient: context.resolveClient,
    }),
  configurePool: (_config, pool) => {
    const configuredAfterCreate = pool.afterCreate;
    return {
      ...pool,
      afterCreate: (
        connection: { execute(sql: string): Promise<unknown> },
        done: (error: unknown, connection?: unknown) => void,
      ) => {
        Promise.all([
          connection.execute(
            `alter session set nls_date_format = 'YYYY-MM-DD HH24:MI:SS'`,
          ),
          connection.execute(
            `alter session set nls_timestamp_format = 'YYYY-MM-DD HH24:MI:SS'`,
          ),
        ])
          .then(() => {
            if (configuredAfterCreate) {
              (
                configuredAfterCreate as unknown as (
                  connection: unknown,
                  done: (error: unknown, connection?: unknown) => void,
                ) => void
              )(connection, done);
            } else done(null, connection);
          })
          .catch((error: unknown) => done(error));
      },
    };
  },
  normalizeConnection: (source) => {
    const config = source as OracleConnectionConfig;
    return {
      ...config,
      host: config.host ?? '127.0.0.1',
      port: config.port ?? 1521,
      serviceName: config.serviceName || 'FREEPDB1',
      username: config.username ?? 'nocobase',
      password: config.password ?? '',
    };
  },
  resolveOwnershipTarget: (source) => {
    const config = source as OracleConnectionConfig;
    return [
      'oracle',
      config.host,
      config.port,
      undefined,
      config.serviceName,
      config.username,
    ];
  },
  resetManagedSchema: async (context) => {
    const client = await context.resolveClient();
    const materializedViews = rawRows<{ name: string }>(
      await client.raw('select mview_name as "name" from user_mviews'),
    );
    const views = rawRows<{ name: string }>(
      await client.raw('select view_name as "name" from user_views'),
    );
    const tables = rawRows<{ name: string }>(
      await client.raw(
        `select t.table_name as "name"
         from user_tables t
         where not exists (
           select 1 from user_mviews m where m.mview_name = t.table_name
         )`,
      ),
    );
    const sequences = rawRows<{ name: string }>(
      await client.raw(
        `select s.sequence_name as "name"
         from user_sequences s
         where not exists (
           select 1
           from user_tab_identity_cols i
           where i.sequence_name = s.sequence_name
         )`,
      ),
    );
    for (const view of materializedViews)
      await client.raw(`drop materialized view ${quoteOracle(view.name)}`);
    for (const view of views)
      await client.raw(`drop view ${quoteOracle(view.name)}`);
    for (const table of tables)
      await client.raw(
        `drop table ${quoteOracle(table.name)} cascade constraints purge`,
      );
    for (const sequence of sequences)
      await client.raw(`drop sequence ${quoteOracle(sequence.name)}`);
  },
};
export type OracleConnection = OracleOptions & {
  dialect: 'oracle';
  databaseDriver: typeof oracleDriver;
};
export interface OracleFactory {
  (options?: OracleOptions): OracleConnection;
  readonly dialect: 'oracle';
  readonly driver: typeof oracleDriver;
}
export const oracle: OracleFactory = Object.assign(
  (options: OracleOptions = { serviceName: 'FREEPDB1' }) => ({
    ...options,
    dialect: 'oracle' as const,
    driver: 'oracledb' as const,
    databaseDriver: oracleDriver,
  }),
  { dialect: 'oracle' as const, driver: oracleDriver },
);
export default oracle;

function quoteOracle(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`;
}

function assertDriverOptions(
  driverOptions: Record<string, unknown> | undefined,
  reservedKeys: readonly string[],
): void {
  if (!driverOptions) return;
  const reserved = reservedKeys.filter(
    (key) => driverOptions[key] !== undefined,
  );
  if (reserved.length > 0) {
    throw new Error(
      `Database driverOptions cannot include ${reserved.join(', ')}. Use flattened connection parameters.`,
    );
  }
}

function compactObject(
  input: Record<string, unknown>,
): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(input).filter(([, value]) => value !== undefined),
  );
}

export { oracleTypes, oracleNumeric } from './inspectors/oracle.js';
