import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { buildConfigFile, generateAuthSecret } from '../src/lib/config-file.ts';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);

/**
 * The real example from the default template, so the placeholders this module rewrites are tested against the file it
 * will actually be handed rather than against a fixture that can quietly diverge from it.
 */
async function readDefaultTemplateExample(): Promise<string> {
  return readFile(
    path.join(
      packageRoot,
      '../../templates/app-template-default/config.example.yml',
    ),
    'utf8',
  );
}

describe('buildConfigFile', () => {
  it('fills in both secrets in the template example', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
      secret: 'test-secret',
    });

    expect(config).toMatch(/^auth:\n(?:\s+#.*\n)*\s+secret: "test-secret"$/mu);
    expect(config).toMatch(
      /^session:\n(?:\s+#.*\n)*\s+secret: "test-secret"$/mu,
    );
    expect(config).not.toContain('replace-with-a-unique-secret');
  });

  /** The example is the only documentation of what an application can be configured with, so none of it is dropped. */
  it('keeps the rest of the example, comments included', async () => {
    const example = await readDefaultTemplateExample();
    const config = buildConfigFile({ example, secret: 'test-secret' });

    expect(config).toContain('# Values under client are public');
    expect(config).toContain('notification:');
    expect(config).toContain('#   llmServices:');
    expect(config).toContain('      dialect: sqlite');
    expect(config).toContain('  workerId: 0');
  });

  /** `client.app.title` names the product rather than the project, so it is left as the template set it. */
  it('leaves everything but the secrets alone', async () => {
    const example = await readDefaultTemplateExample();
    const config = buildConfigFile({ example, secret: 'test-secret' });

    expect(config).toContain('    title: NocoBase');
    expect(
      example
        .split('\n')
        .filter(
          (line) =>
            !line.includes('replace-with-a-unique-secret') &&
            !line.includes('Copy this file'),
        )
        .every((line) => config.includes(line)),
    ).toBe(true);
  });

  it('replaces the example instruction with a generated-by header', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
    });

    expect(config.split('\n')[0]).toBe('# Generated by @nocobase/create-app.');
    expect(config).not.toContain('Copy this file to config.yml');
  });

  it('uncomments a section that is commented out in its entirety', () => {
    const config = buildConfigFile({
      secret: 'test-secret',
      example: [
        'auth:',
        '  # secret: replace-with-a-unique-secret',
        '  emailAndPassword:',
        '    enabled: true',
        '',
        '# session:',
        '#   # Use the same generated value as auth.secret.',
        '#   secret: replace-with-a-unique-secret',
        '',
        'snowflake:',
        '  workerId: 0',
        '',
      ].join('\n'),
    });

    expect(config).toContain(
      [
        'session:',
        '  # Use the same generated value as auth.secret.',
        '  secret: "test-secret"',
      ].join('\n'),
    );
    // The section below the uncommented one is untouched, so the file still parses as the same document.
    expect(config).toContain('snowflake:\n  workerId: 0');
  });

  it('replaces a secret the example already sets', () => {
    const config = buildConfigFile({
      secret: 'test-secret',
      example: [
        'auth:',
        '  secret: stale',
        'session:',
        '  secret: stale',
        '',
      ].join('\n'),
    });

    expect(config).not.toContain('stale');
    expect(config.match(/secret: "test-secret"/gu)).toHaveLength(2);
  });

  /** A template is free not to mention the secrets at all, and the generated file still has to carry them. */
  it('inserts a section the example does not have', () => {
    const config = buildConfigFile({
      secret: 'test-secret',
      example: 'snowflake:\n  workerId: 0\n',
    });

    expect(config).toContain('auth:\n  secret: "test-secret"');
    expect(config).toContain('session:\n  secret: "test-secret"');
    expect(config).toContain('snowflake:\n  workerId: 0');
  });

  /** Nothing about `auth.session` makes it the top-level `session` section. */
  it('does not mistake a nested key for the section of the same name', () => {
    const config = buildConfigFile({
      secret: 'test-secret',
      example: [
        'auth:',
        '  # secret: replace-with-a-unique-secret',
        '  session:',
        '    storeSessionInDatabase: true',
        '',
      ].join('\n'),
    });

    expect(config).toContain('  session:\n    storeSessionInDatabase: true');
    expect(config).toContain('session:\n  secret: "test-secret"');
    expect(config).not.toContain('storeSessionInDatabase: true\n    secret');
  });

  it('falls back to a minimal file when the template ships no example', () => {
    const config = buildConfigFile({ secret: 'test-secret' });

    expect(config).toContain('# Generated by @nocobase/create-app.');
    expect(config).toContain('auth:\n  secret: "test-secret"');
    expect(config).toContain('session:\n  secret: "test-secret"');
  });

  it('generates a secret when none is given, and the same one for both sections', () => {
    const config = buildConfigFile();
    const secrets = [...config.matchAll(/secret: "([^"]+)"/gu)].map(
      (match) => match[1],
    );

    expect(secrets).toHaveLength(2);
    expect(secrets[0]).toBe(secrets[1]);
    expect(secrets[0]).not.toBe('');
    expect(buildConfigFile()).not.toBe(config);
  });

  it('ends with exactly one trailing newline', () => {
    expect(buildConfigFile({ secret: 'x' })).toMatch(/[^\n]\n$/u);
  });
});

describe('generateAuthSecret', () => {
  it('generates a distinct URL-safe secret each time', () => {
    const secret = generateAuthSecret();

    expect(secret).toMatch(/^[A-Za-z0-9_-]+$/u);
    expect(secret).not.toBe(generateAuthSecret());
  });
});
