import { OpenAPIHono, createRoute } from "@hono/zod-openapi";
import { ChecksumSchema, CompleteUploadResultSchema, CreateUploadResultSchema, FilesErrorCodeSchema, PublicFilesConfigSchema, SuccessEnvelopeSchema } from "../contracts/index.ts";
import { createPublicFilesConfig, type DriverCapabilities, type ValidatedFilesConfig } from "../config/index.ts";
import { resolveFilesRequestContext } from "../authorization/index.ts";
import type { FileRequestContextResolver } from "../module-types.ts";
import { filesErrorResponse } from "../errors/index.ts";
import type { UploadService } from "../application/upload-service.ts";
import { z } from "zod";

export interface CreateFilesRouterFoundationOptions { config: ValidatedFilesConfig; requestContext: FileRequestContextResolver; getDriverCapabilities: () => DriverCapabilities[]; logger?: { error(error: unknown): void }; uploads?: UploadService }
export function createFilesOpenAPIApp(options: CreateFilesRouterFoundationOptions) {
  const app = new OpenAPIHono();
  app.openapi(createRoute({ method: "get", path: "/config", operationId: "filesGetConfig", responses: { 200: { content: { "application/json": { schema: SuccessEnvelopeSchema(PublicFilesConfigSchema) } }, description: "Public files configuration" }, 401: { description: "Unauthorized" }, 403: { description: "Forbidden" }, 500: { description: "Internal error" } } }), (async (c: any) => {
    try { await resolveFilesRequestContext(c, options.requestContext); return c.json({ data: createPublicFilesConfig(options.config, options.getDriverCapabilities()) }, 200); } catch (e) { const m = filesErrorResponse(e); options.logger?.error(e); return c.json(m.body, m.status as 403); }
  }) as any);
  if (!options.uploads) return app;
  const error = { content: { "application/json": { schema: z.object({ error: z.object({ code: FilesErrorCodeSchema, message: z.string(), retryable: z.boolean(), requestId: z.string().optional(), details: z.object({}).passthrough().optional() }).strict() }).strict() } }, description: "Error" } as const;
  const createInput = z.object({ policy: z.string().min(1).optional(), originalName: z.string().min(1), contentType: z.string().min(1), size: z.number().int().positive(), checksum: ChecksumSchema.optional(), context: z.object({}).passthrough().optional() }).strict();
  app.openapi(createRoute({ method: "post", path: "/uploads", operationId: "filesCreateUpload", request: { headers: z.object({ "Idempotency-Key": z.string().min(1).max(256) }), body: { required: true, content: { "application/json": { schema: createInput } } } }, responses: { 201: { content: { "application/json": { schema: SuccessEnvelopeSchema(CreateUploadResultSchema) } }, description: "Upload created" }, 400: error, 403: error, 409: error, 410: error, 413: error, 415: error, 500: error, 503: error } }), (async (c: any) => { try { const { actor, workspaceId } = await resolveFilesRequestContext(c, options.requestContext); const key = c.req.header("Idempotency-Key"); if (!key) throw new Error("FILES_INVALID_REQUEST"); const data = await options.uploads!.create(actor, workspaceId, key, await c.req.json()); if (data.target.url.startsWith("/")) data.target.url = new URL(data.target.url, c.req.url).href; return c.json({ data }, 201); } catch (e) { const m = filesErrorResponse(e); options.logger?.error(e); return c.json(m.body, m.status); } }) as any);
  app.openapi(createRoute({ method: "put", path: "/uploads/{uploadId}/content", operationId: "filesUploadProxyContent", request: { params: z.object({ uploadId: z.string().min(1) }), query: z.object({ token: z.string().min(1) }), body: { required: true, content: { "application/octet-stream": { schema: z.string().openapi({ format: "binary" }) } } } }, responses: { 204: { description: "Content stored" }, 400: error, 403: error, 404: error, 409: error, 410: error, 415: error, 500: error, 503: error } }), (async (c: any) => { try { const workspaceId = await options.requestContext.getWorkspaceId(c); if (!workspaceId?.trim()) throw new Error("FILES_INVALID_REQUEST"); const token = c.req.query("token"); if (!token || !c.req.raw.body) throw new Error("FILES_INVALID_REQUEST"); await options.uploads!.proxy(workspaceId, c.req.param("uploadId"), token, c.req.raw.headers, c.req.raw.body); return new Response(null, { status: 204 }); } catch (e) { const m = filesErrorResponse(e); options.logger?.error(e); return c.json(m.body, m.status); } }) as any);
  app.openapi(createRoute({ method: "post", path: "/uploads/{uploadId}/complete", operationId: "filesCompleteUpload", request: { params: z.object({ uploadId: z.string().min(1) }) }, responses: { 200: { content: { "application/json": { schema: SuccessEnvelopeSchema(CompleteUploadResultSchema) } }, description: "Upload completed" }, 403: error, 404: error, 409: error, 410: error, 415: error, 500: error, 503: error } }), (async (c: any) => { try { const { actor, workspaceId } = await resolveFilesRequestContext(c, options.requestContext); return c.json({ data: await options.uploads!.complete(actor, workspaceId, c.req.param("uploadId")) }, 200); } catch (e) { const m = filesErrorResponse(e); options.logger?.error(e); return c.json(m.body, m.status); } }) as any);
  return app;
}
